// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { ClientFacingBloodOxygenTimeseries } from "../../../types/ClientFacingBloodOxygenTimeseries.js";

export const Response: core.serialization.Schema<
    serializers.vitals.bloodOxygen.Response.Raw,
    Vital.ClientFacingBloodOxygenTimeseries[]
> = core.serialization.list(ClientFacingBloodOxygenTimeseries);

export declare namespace Response {
    export type Raw = ClientFacingBloodOxygenTimeseries.Raw[];
}
