// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { ClientFacingCaffeineTimeseries } from "../../../types/ClientFacingCaffeineTimeseries.js";

export const Response: core.serialization.Schema<
    serializers.vitals.caffeine.Response.Raw,
    Vital.ClientFacingCaffeineTimeseries[]
> = core.serialization.list(ClientFacingCaffeineTimeseries);

export declare namespace Response {
    export type Raw = ClientFacingCaffeineTimeseries.Raw[];
}
