/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Vital from "../../../../api";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.vitals.hrv.Response.Raw,
    Vital.ClientFacingHrvTimeseries[]
> = core.serialization.list(
    core.serialization.lazyObject(async () => (await import("../../..")).ClientFacingHrvTimeseries)
);

export declare namespace Response {
    type Raw = serializers.ClientFacingHrvTimeseries.Raw[];
}
