/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Vital from "../../../../api/index";
import * as core from "../../../../core";
import { ClientFacingHypnogramTimeseries } from "../../../types/ClientFacingHypnogramTimeseries";

export const Response: core.serialization.Schema<
    serializers.vitals.hypnogram.Response.Raw,
    Vital.ClientFacingHypnogramTimeseries[]
> = core.serialization.list(ClientFacingHypnogramTimeseries);

export declare namespace Response {
    type Raw = ClientFacingHypnogramTimeseries.Raw[];
}
