// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { ClientFacingVo2MaxTimeseries } from "../../../types/ClientFacingVo2MaxTimeseries.js";

export const Response: core.serialization.Schema<
    serializers.vitals.vo2Max.Response.Raw,
    Vital.ClientFacingVo2MaxTimeseries[]
> = core.serialization.list(ClientFacingVo2MaxTimeseries);

export declare namespace Response {
    export type Raw = ClientFacingVo2MaxTimeseries.Raw[];
}
