export { ActivityApi } from './Activity';
export { BodyApi } from './Body';
export { LinkApi } from './Link';
export { SleepApi } from './Sleep';
export { UserApi } from './User';
export { WebhooksApi } from './Webhooks';
export { WorkoutsApi } from './Workouts';
export { OrdersApi, TestsApi, ResultsApi } from './Testing';
export { ProfileApi } from './Profile';
export { DevicesAPI } from './Devices';
