// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { OAuthProviders } from "../../../../types/OAuthProviders.js";

export const BulkExportConnectionsBody: core.serialization.Schema<
    serializers.BulkExportConnectionsBody.Raw,
    Omit<Vital.BulkExportConnectionsBody, "teamId">
> = core.serialization.object({
    userIds: core.serialization.property("user_ids", core.serialization.list(core.serialization.string()).optional()),
    provider: OAuthProviders,
    nextToken: core.serialization.property("next_token", core.serialization.string().optional()),
});

export declare namespace BulkExportConnectionsBody {
    export interface Raw {
        user_ids?: string[] | null;
        provider: OAuthProviders.Raw;
        next_token?: string | null;
    }
}
