// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const CompletePasswordProviderMfaBody: core.serialization.Schema<
    serializers.CompletePasswordProviderMfaBody.Raw,
    Omit<Vital.CompletePasswordProviderMfaBody, "vitalLinkToken">
> = core.serialization.object({
    mfaCode: core.serialization.property("mfa_code", core.serialization.string()),
});

export declare namespace CompletePasswordProviderMfaBody {
    export interface Raw {
        mfa_code: string;
    }
}
