/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as Vital from "../../../../../api";
import * as core from "../../../../../core";
import { Providers } from "../../../../types/Providers";
import { AuthType } from "../../../../types/AuthType";
import { Region } from "../../../../types/Region";

export const EmailAuthLink: core.serialization.Schema<
    serializers.EmailAuthLink.Raw,
    Omit<Vital.EmailAuthLink, "vitalLinkToken">
> = core.serialization.object({
    email: core.serialization.string(),
    provider: Providers,
    authType: core.serialization.property("auth_type", AuthType),
    region: Region.optional(),
});

export declare namespace EmailAuthLink {
    interface Raw {
        email: string;
        provider: Providers.Raw;
        auth_type: AuthType.Raw;
        region?: Region.Raw | null;
    }
}
