/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors";
import * as Vital from "..";

export class BadRequestError extends errors.VitalError {
    constructor(body: Vital.UserRefreshErrorResponse) {
        super({
            statusCode: 400,
            body: body,
        });
        Object.setPrototypeOf(this, BadRequestError.prototype);
    }
}
