/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "../../../..";

export interface CreateLabTestRequest {
    markerIds: number[];
    labId: number;
    name: string;
    method: Vital.LabTestCollectionMethod;
    sampleType: Vital.LabTestSampleType;
    description: string;
    fasting?: boolean;
}
