/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "../../../..";

/**
 * @example
 *     {}
 */
export interface LabTestsGetOrdersRequest {
    /**
     * Search by order id, user id, patient name, shipping dob, or shipping recipient name.
     */
    searchInput?: string;
    /**
     * Date from in YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 00:00:00
     */
    startDate?: Date;
    /**
     * Date to YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 23:59:59
     */
    endDate?: Date;
    /**
     * Date from in YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 00:00:00
     */
    updatedStartDate?: Date;
    /**
     * Date to YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 00:00:00
     */
    updatedEndDate?: Date;
    orderKey?: Vital.LabTestsGetOrdersRequestOrderKey;
    orderDirection?: Vital.LabTestsGetOrdersRequestOrderDirection;
    /**
     * Filter by user ID.
     */
    userId?: string;
    /**
     * Filter by patient name.
     */
    patientName?: string;
    /**
     * Filter by shipping recipient name.
     */
    shippingRecipientName?: string;
    /**
     * Filter by order ids.
     */
    orderIds?: string | string[];
    page?: number;
    size?: number;
}
