/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface LabTestsGetByIdRequest {
    /**
     * The lab account ID. This lab account is used to determine the availability of markers and lab tests.
     */
    labAccountId?: string;
}
