/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface LabTestsGetMarkersRequest {
    /**
     * The identifier Vital assigned to a lab partner.
     */
    labId?: number | number[];
    /**
     * The name or test code of an individual biomarker or a panel.
     */
    name?: string;
    aLaCarteEnabled?: boolean;
    /**
     * The lab account ID. This lab account is used to determine the availability of markers and lab tests.
     */
    labAccountId?: string;
    page?: number;
    size?: number;
}
