/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "../../../..";

/**
 * @example
 *     {
 *         zipCode: "zip_code"
 *     }
 */
export interface LabTestsGetAreaInfoRequest {
    /**
     * Zip code of the area to check
     */
    zipCode: string;
    /**
     * Radius in which to search (meters)
     */
    radius?: Vital.AllowedRadius;
}
