/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "../../../..";

export interface RequestAppointmentRequest {
    /** At-home phlebotomy appointment address. */
    address: Vital.UsAddress;
    provider: Vital.AppointmentProvider;
}
