/* tslint:disable */
/* eslint-disable */
/**
 * Vital
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */export * from './apis/activity-api';
export * from './apis/body-api';
export * from './apis/link-api';
export * from './apis/provider-specific-api';
export * from './apis/sleep-api';
export * from './apis/user-api';
export * from './apis/webhooks-api';
export * from './apis/workouts-api';

