/* tslint:disable */
/* eslint-disable */
/**
 * Vital
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ClientFacingSourceSpecific
 */
export interface ClientFacingSourceSpecific {
    /**
     * 
     * @type {string}
     * @memberof ClientFacingSourceSpecific
     */
    id: any;
    /**
     * Date for specified record
     * @type {Date}
     * @memberof ClientFacingSourceSpecific
     */
    date: any;
    /**
     * Type of data, activity/sleep/workouts/body
     * @type {string}
     * @memberof ClientFacingSourceSpecific
     */
    type: any;
    /**
     * JSON data that is specific to the device
     * @type {any | string}
     * @memberof ClientFacingSourceSpecific
     */
    data: any;
    /**
     * User key returned by vital create user key request. This key should be stored in your database against the user and used for all interactions with the vital api.
     * @type {string}
     * @memberof ClientFacingSourceSpecific
     */
    userId: any;
}
