/* tslint:disable */
/* eslint-disable */
/**
 * Vital
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ClientFacingActivity
 */
export interface ClientFacingActivity {
    /**
     * 
     * @type {string}
     * @memberof ClientFacingActivity
     */
    id: any;
    /**
     * Date for specified record
     * @type {Date}
     * @memberof ClientFacingActivity
     */
    date: any;
    /**
     * Total energy consumption during the day including Basal Metabolic Rate in kilocalories.::kilocalories
     * @type {number}
     * @memberof ClientFacingActivity
     */
    caloriesTotal: any;
    /**
     * Energy consumption caused by the physical activity of the day in kilocalories.::kilocalories
     * @type {number}
     * @memberof ClientFacingActivity
     */
    caloriesActive: any;
    /**
     * Total number of steps registered during the day.::steps
     * @type {number}
     * @memberof ClientFacingActivity
     */
    steps?: any;
    /**
     * Daily physical activity as equal meters i.e. amount of walking needed to get the same amount of activity.::meters
     * @type {number}
     * @memberof ClientFacingActivity
     */
    dailyMovement?: any;
    /**
     * Number of minutes during the day with low intensity activity (e.g. household work).::minutes
     * @type {number}
     * @memberof ClientFacingActivity
     */
    low?: any;
    /**
     * Number of minutes during the day with medium intensity activity (e.g. walking).::minutes
     * @type {number}
     * @memberof ClientFacingActivity
     */
    medium?: any;
    /**
     * Number of minutes during the day with high intensity activity (e.g. running).::minutes
     * @type {number}
     * @memberof ClientFacingActivity
     */
    high?: any;
    /**
     * Source the data has come from.
     * @type {SourceClientFacing}
     * @memberof ClientFacingActivity
     */
    source: any;
    /**
     * User key returned by vital create user key request. This key should be stored in your database against the user and used for all interactions with the vital api.
     * @type {string}
     * @memberof ClientFacingActivity
     */
    userId: any;
}
