/* tslint:disable */
/* eslint-disable */
/**
 * Vital
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { ClientActivityResponse } from '../models';
import { HTTPValidationError } from '../models';
/**
 * ActivityApi - axios parameter creator
 * @export
 */
export const ActivityApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get Daily Activity for user_key
         * @summary Get User Activity
         * @param {string} userKey 
         * @param {Date} endDate Date to in YYYY-MM-DD
         * @param {Date} startDate Date from in YYYY-MM-DD
         * @param {string} [provider] Provider oura/strava etc.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserActivity: async (userKey: string, endDate: Date, startDate: Date, provider?: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'userKey' is not null or undefined
            if (userKey === null || userKey === undefined) {
                throw new RequiredError('userKey','Required parameter userKey was null or undefined when calling getUserActivity.');
            }
            // verify required parameter 'endDate' is not null or undefined
            if (endDate === null || endDate === undefined) {
                throw new RequiredError('endDate','Required parameter endDate was null or undefined when calling getUserActivity.');
            }
            // verify required parameter 'startDate' is not null or undefined
            if (startDate === null || startDate === undefined) {
                throw new RequiredError('startDate','Required parameter startDate was null or undefined when calling getUserActivity.');
            }
            const localVarPath = `/v1/activity/{user_key}`
                .replace(`{${"user_key"}}`, encodeURIComponent(String(userKey)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (endDate !== undefined) {
                localVarQueryParameter['end_date'] = (endDate as any instanceof Date) ?
                    (endDate as any).toISOString() :
                    endDate;
            }

            if (provider !== undefined) {
                localVarQueryParameter['provider'] = provider;
            }

            if (startDate !== undefined) {
                localVarQueryParameter['start_date'] = (startDate as any instanceof Date) ?
                    (startDate as any).toISOString() :
                    startDate;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ActivityApi - functional programming interface
 * @export
 */
export const ActivityApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Get Daily Activity for user_key
         * @summary Get User Activity
         * @param {string} userKey 
         * @param {Date} endDate Date to in YYYY-MM-DD
         * @param {Date} startDate Date from in YYYY-MM-DD
         * @param {string} [provider] Provider oura/strava etc.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserActivity(userKey: string, endDate: Date, startDate: Date, provider?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ClientActivityResponse>> {
            const localVarAxiosArgs = await ActivityApiAxiosParamCreator(configuration).getUserActivity(userKey, endDate, startDate, provider, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ActivityApi - factory interface
 * @export
 */
export const ActivityApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Get Daily Activity for user_key
         * @summary Get User Activity
         * @param {string} userKey 
         * @param {Date} endDate Date to in YYYY-MM-DD
         * @param {Date} startDate Date from in YYYY-MM-DD
         * @param {string} [provider] Provider oura/strava etc.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserActivity(userKey: string, endDate: Date, startDate: Date, provider?: string, options?: any): AxiosPromise<ClientActivityResponse> {
            return ActivityApiFp(configuration).getUserActivity(userKey, endDate, startDate, provider, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ActivityApi - object-oriented interface
 * @export
 * @class ActivityApi
 * @extends {BaseAPI}
 */
export class ActivityApi extends BaseAPI {
    /**
     * Get Daily Activity for user_key
     * @summary Get User Activity
     * @param {string} userKey 
     * @param {Date} endDate Date to in YYYY-MM-DD
     * @param {Date} startDate Date from in YYYY-MM-DD
     * @param {string} [provider] Provider oura/strava etc.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ActivityApi
     */
    public getUserActivity(userKey: string, endDate: Date, startDate: Date, provider?: string, options?: any) {
        return ActivityApiFp(this.configuration).getUserActivity(userKey, endDate, startDate, provider, options).then((request) => request(this.axios, this.basePath));
    }
}
