// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../../../index.js";

/**
 * @example
 *     {
 *         name: "name",
 *         address: {
 *             firstLine: "first_line",
 *             country: "country",
 *             zip: "zip",
 *             city: "city",
 *             state: "state"
 *         }
 *     }
 */
export interface CreatePayorBody {
    name: string;
    address: Vital.Address;
    provider?: Vital.PayorCodeExternalProvider;
    providerPayorId?: string;
}
