// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         userId: "user_id",
 *         clientUserId: "client_user_id"
 *     }
 */
export interface UserUndoDeleteRequest {
    /** User ID to undo deletion. Mutually exclusive with `client_user_id`. */
    userId?: string;
    /** Client User ID to undo deletion. Mutually exclusive with `user_id`. */
    clientUserId?: string;
}
