// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         offset: 1,
 *         limit: 1
 *     }
 */
export interface UserGetAllRequest {
    offset?: number;
    limit?: number;
}
