// This file was auto-generated by Fern from our API Definition.

export const LinkBulkExportRequestTeamId = {
    InferFromContext: "infer_from_context",
} as const;
export type LinkBulkExportRequestTeamId =
    (typeof LinkBulkExportRequestTeamId)[keyof typeof LinkBulkExportRequestTeamId];
