// This file was auto-generated by Fern from our API Definition.

export const LinkListBulkOpsRequestTeamId = {
    InferFromContext: "infer_from_context",
} as const;
export type LinkListBulkOpsRequestTeamId =
    (typeof LinkListBulkOpsRequestTeamId)[keyof typeof LinkListBulkOpsRequestTeamId];
