/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "../../../../index";

/**
 * @example
 *     {
 *         userIds: ["user_ids"],
 *         provider: "oura"
 *     }
 */
export interface BulkTriggerHistoricalPullBody {
    teamId?: Vital.LinkBulkTriggerHistoricalPullRequestTeamId;
    userIds: string[];
    provider: Vital.OAuthProviders;
    /**
     * Whether or not the endpoint should wait for the Bulk Op to complete before responding.
     *
     * When `wait_for_completion` is enabled, the endpoint may respond 200 OK if the Bulk Op takes less than 20 seconds to complete.
     *
     * Otherwise, the endpoint always responds with 202 Created once the submitted data have been enqueued successfully. You can use
     * the [List Bulk Ops](https://docs.tryvital.io/api-reference/link/list-bulk-ops) endpoint to inspect the progress of the Bulk Op.
     */
    waitForCompletion?: boolean;
}
