/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         userId: "user_id"
 *     }
 */
export interface CodeCreateLinkRequest {
    userId: string;
    /**
     * When the link code should expire. Defaults to server time plus 1 hour.
     */
    expiresAt?: Date;
}
