/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         mfaCode: "mfa_code"
 *     }
 */
export interface CompletePasswordProviderMfaBody {
    vitalLinkToken?: string;
    mfaCode: string;
}
