/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "../../../..";

/**
 * @example
 *     {
 *         email: "email",
 *         provider: Vital.Providers.Oura,
 *         authType: Vital.AuthType.Password
 *     }
 */
export interface EmailAuthLink {
    vitalLinkToken?: string;
    email: string;
    provider: Vital.Providers;
    authType: Vital.AuthType;
    region?: Vital.Region;
}
