/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "../../../..";

/**
 * @example
 *     {
 *         email: "email"
 *     }
 */
export interface EmailProviderAuthLink {
    vitalLinkToken?: string;
    email: string;
    emailProviderAuthLinkProvider?: Vital.Providers;
    region?: Vital.Region;
}
