// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const CreateUserPortalUrlBodyContext: core.serialization.Schema<
    serializers.CreateUserPortalUrlBodyContext.Raw,
    Vital.CreateUserPortalUrlBodyContext
> = core.serialization.enum_(["launch", "communications"]);

export declare namespace CreateUserPortalUrlBodyContext {
    export type Raw = "launch" | "communications";
}
