/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Vital from "../../../../api";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.labTests.getPhlebotomyAppointmentCancellationReason.Response.Raw,
    Vital.ClientFacingAppointmentCancellationReason[]
> = core.serialization.list(
    core.serialization.lazyObject(async () => (await import("../../..")).ClientFacingAppointmentCancellationReason)
);

export declare namespace Response {
    type Raw = serializers.ClientFacingAppointmentCancellationReason.Raw[];
}
