/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Vital from "../../../../api/index";
import * as core from "../../../../core";
import { SimulationFlags } from "../../../types/SimulationFlags";

export const Request: core.serialization.Schema<
    serializers.labTests.simulateOrderProcess.Request.Raw,
    Vital.SimulationFlags | undefined
> = SimulationFlags.optional();

export declare namespace Request {
    type Raw = SimulationFlags.Raw | null | undefined;
}
