/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Vital from "../../../../api/index";
import * as core from "../../../../core";
import { ClientFacingPayorSearchResponseDeprecated } from "../../../types/ClientFacingPayorSearchResponseDeprecated";

export const Response: core.serialization.Schema<
    serializers.insurance.searchPayorInfo.Response.Raw,
    Vital.ClientFacingPayorSearchResponseDeprecated[]
> = core.serialization.list(ClientFacingPayorSearchResponseDeprecated);

export declare namespace Response {
    type Raw = ClientFacingPayorSearchResponseDeprecated.Raw[];
}
