/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Addres {
    use: string;
    type: string;
    line: string[];
    city: string;
    state: string;
    postalCode: string;
    country: string;
}
