// This file was auto-generated by Fern from our API Definition.

/** ℹ️ This enum is non-exhaustive. */
export const AppointmentType = {
    Phlebotomy: "phlebotomy",
    PatientServiceCenter: "patient_service_center",
} as const;
export type AppointmentType = (typeof AppointmentType)[keyof typeof AppointmentType];
