/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An enumeration.
 */
export type AppointmentStatus = "confirmed" | "pending" | "in_progress" | "completed" | "cancelled";

export const AppointmentStatus = {
    Confirmed: "confirmed",
    Pending: "pending",
    InProgress: "in_progress",
    Completed: "completed",
    Cancelled: "cancelled",
} as const;
