/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "../index";

export interface AreaInfo {
    zipCode: string;
    phlebotomy: Vital.PhlebotomyAreaInfo;
    centralLabs: Record<string, Vital.PscAreaInfo>;
}
