// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../index.js";

export interface AreaInfo {
    zipCode: string;
    phlebotomy: Vital.PhlebotomyAreaInfo;
    centralLabs: Record<string, Vital.PscAreaInfo>;
}
