/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * ℹ️ This enum is non-exhaustive.
 */
export type BodyColumnExprBody =
    | "measured_at"
    | "weight_kilogram"
    | "fat_mass_percentage"
    | "water_percentage"
    | "muscle_mass_percentage"
    | "visceral_fat_index"
    | "bone_mass_percentage"
    | "body_mass_index"
    | "lean_body_mass_kilogram"
    | "waist_circumference_centimeter"
    | "source_type"
    | "source_provider"
    | "source_app_id"
    | "time_zone";

export const BodyColumnExprBody = {
    MeasuredAt: "measured_at",
    WeightKilogram: "weight_kilogram",
    FatMassPercentage: "fat_mass_percentage",
    WaterPercentage: "water_percentage",
    MuscleMassPercentage: "muscle_mass_percentage",
    VisceralFatIndex: "visceral_fat_index",
    BoneMassPercentage: "bone_mass_percentage",
    BodyMassIndex: "body_mass_index",
    LeanBodyMassKilogram: "lean_body_mass_kilogram",
    WaistCircumferenceCentimeter: "waist_circumference_centimeter",
    SourceType: "source_type",
    SourceProvider: "source_provider",
    SourceAppId: "source_app_id",
    TimeZone: "time_zone",
} as const;
