/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "../index";

export interface CervicalMucusEntry {
    date: string;
    /** ℹ️ This enum is non-exhaustive. */
    quality: Vital.CervicalMucusEntryQuality;
}
