// This file was auto-generated by Fern from our API Definition.

export const ClientFacingMindfulnessMinutesChangedEventType = {
    DailyDataMindfulnessMinutesCreated: "daily.data.mindfulness_minutes.created",
    DailyDataMindfulnessMinutesUpdated: "daily.data.mindfulness_minutes.updated",
} as const;
export type ClientFacingMindfulnessMinutesChangedEventType =
    (typeof ClientFacingMindfulnessMinutesChangedEventType)[keyof typeof ClientFacingMindfulnessMinutesChangedEventType];
