// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../index.js";

export interface ClientFacingDevice {
    id: string;
    userId: string;
    provider: string;
    /** ℹ️ This enum is non-exhaustive. */
    sourceType: Vital.ClientFacingDeviceSourceType;
    appId?: string;
    deviceManufacturer?: string;
    deviceModel?: string;
    deviceVersion?: string;
    deviceId?: string;
}
