// This file was auto-generated by Fern from our API Definition.

export const ClientFacingCaloriesActiveChangedEventType = {
    DailyDataCaloriesActiveCreated: "daily.data.calories_active.created",
    DailyDataCaloriesActiveUpdated: "daily.data.calories_active.updated",
} as const;
export type ClientFacingCaloriesActiveChangedEventType =
    (typeof ClientFacingCaloriesActiveChangedEventType)[keyof typeof ClientFacingCaloriesActiveChangedEventType];
