/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ClientFacingFloorsClimbedTimeseries {
    id?: number;
    timezoneOffset?: number;
    type?: string;
    /** Measured in counts */
    unit: "count";
    /** The timestamp of the measurement. */
    timestamp: Date;
    /** Number of floors climbed at the time or interval::count */
    value: number;
}
