/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "../index";

export interface ClientFacingForcedVitalCapacityHistoricalPullCompleted {
    eventType: "historical.data.forced_vital_capacity.created";
    userId: string;
    clientUserId: string;
    teamId: string;
    data: Vital.HistoricalPullCompleted;
}
