// This file was auto-generated by Fern from our API Definition.

export const ClientFacingLeanBodyMassChangedEventType = {
    DailyDataLeanBodyMassCreated: "daily.data.lean_body_mass.created",
    DailyDataLeanBodyMassUpdated: "daily.data.lean_body_mass.updated",
} as const;
export type ClientFacingLeanBodyMassChangedEventType =
    (typeof ClientFacingLeanBodyMassChangedEventType)[keyof typeof ClientFacingLeanBodyMassChangedEventType];
