/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ClientFacingWorkoutDurationSampleIntensity = "low" | "medium" | "high";

export const ClientFacingWorkoutDurationSampleIntensity = {
    Low: "low",
    Medium: "medium",
    High: "high",
} as const;
