/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "..";

export interface ClientFacingMarker {
    id: number;
    name: string;
    slug: string;
    description?: string;
    labId?: number;
    providerId?: string;
    type?: Vital.MarkerType;
    unit?: string;
    price?: string;
    aoe?: Vital.AoE;
}
