/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ClientFacingElectrocardiogramClassification = "sinus_rhythm" | "atrial_fibrillation" | "inconclusive";

export const ClientFacingElectrocardiogramClassification = {
    SinusRhythm: "sinus_rhythm",
    AtrialFibrillation: "atrial_fibrillation",
    Inconclusive: "inconclusive",
} as const;
