/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "../index";

export interface ClientFacingAfibBurdenHistoricalPullCompleted {
    eventType: "historical.data.afib_burden.created";
    userId: string;
    clientUserId: string;
    teamId: string;
    data: Vital.HistoricalPullCompleted;
}
