/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ClientFacingHeartRate {
    avgBpm?: number;
    minBpm?: number;
    maxBpm?: number;
    restingBpm?: number;
}
