/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ClientFacingWheelchairPushChangedEventType =
    | "daily.data.wheelchair_push.created"
    | "daily.data.wheelchair_push.updated";

export const ClientFacingWheelchairPushChangedEventType = {
    DailyDataWheelchairPushCreated: "daily.data.wheelchair_push.created",
    DailyDataWheelchairPushUpdated: "daily.data.wheelchair_push.updated",
} as const;
