// This file was auto-generated by Fern from our API Definition.

/**
 * Schema for a Shipment in the client facing API.
 *
 * To be used as part of a ClientFacingTestkitOrder.
 */
export interface ClientFacingShipment {
    /** The Vital Shipment ID */
    id: string;
    /** Tracking number for delivery to customer */
    outboundTrackingNumber?: string;
    /** Tracking url for delivery to customer */
    outboundTrackingUrl?: string;
    /** Tracking number for delivery to lab */
    inboundTrackingNumber?: string;
    /** Tracking url for delivery to lab */
    inboundTrackingUrl?: string;
    /** Courier used for delivery to customer */
    outboundCourier?: string;
    /** Courier used for delivery to lab */
    inboundCourier?: string;
    /** Notes associated to the Vital shipment */
    notes?: string;
}
