/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ClientFacingFatChangedEventType = "daily.data.fat.created" | "daily.data.fat.updated";

export const ClientFacingFatChangedEventType = {
    DailyDataFatCreated: "daily.data.fat.created",
    DailyDataFatUpdated: "daily.data.fat.updated",
} as const;
