/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ClientFacingConnectionErrorDetailsErrorType =
    | "token_refresh_failed"
    | "webhook_registration_failed"
    | "user_not_found"
    | "deregistered_per_provider"
    | "required_scopes_not_granted"
    | "provider_credential_error"
    | "unknown";

export const ClientFacingConnectionErrorDetailsErrorType = {
    TokenRefreshFailed: "token_refresh_failed",
    WebhookRegistrationFailed: "webhook_registration_failed",
    UserNotFound: "user_not_found",
    DeregisteredPerProvider: "deregistered_per_provider",
    RequiredScopesNotGranted: "required_scopes_not_granted",
    ProviderCredentialError: "provider_credential_error",
    Unknown: "unknown",
} as const;
