/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "../index";

export interface ClientFacingForcedVitalCapacityChanged {
    eventType: Vital.ClientFacingForcedVitalCapacityChangedEventType;
    userId: string;
    clientUserId: string;
    teamId: string;
    data: Vital.VitalCoreSchemasResponseSchemasTimeseriesClientFacingTimeseriesGroupClientFacingForcedVitalCapacitySample;
}
