/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "../index";

export interface ClientFacingDeviceChanged {
    eventType: Vital.ClientFacingDeviceChangedEventType;
    userId: string;
    clientUserId: string;
    teamId: string;
    data: Vital.ClientFacingDevice;
}
