// This file was auto-generated by Fern from our API Definition.

/**
 * A vendor, a service, or a platform which Vital can connect with.
 */
export interface ClientFacingProvider {
    /** Name of source of information */
    name: string;
    /** Slug for designated source */
    slug: string;
    /** URL for source logo */
    logo: string;
}
