/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ClientFacingCriticalResult {
    /** The Vital Order ID */
    orderId: string;
    /** Sample ID */
    sampleId: string;
    /** The current results status, can be either (final, partial). */
    status: string;
    /** The results interpretation, can be either (normal, abnormal, critical). */
    interpretation: string;
    /** Your team id. */
    teamId: string;
    userId: string;
    /** When the result was first fetched from a laboratory. */
    createdAt: Date;
    /** When the result was last fetched from a laboratory. */
    updatedAt: Date;
}
