/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Source summarizes where a sample or a summary is sourced from.
 * At minimum, the source provider is always included.
 */
export interface ClientFacingSource {
    /** Provider slug. e.g., `oura`, `fitbit`, `garmin`. */
    provider: string;
    /** The type of the data source (app or device) by which the summary or the timeseries data were recorded. This defaults to `unknown` when Vital cannot extract or infer that information */
    type?: string;
    appId?: string;
    /** Deprecated. Subject to removal after 1 Jan 2024. */
    name: string;
    /** Deprecated. Use `provider` instead. Subject to removal after 1 Jan 2024. */
    slug: string;
    /** Deprecated. Subject to removal after 1 Jan 2024. */
    logo: string;
}
