/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "../index";

export interface ClientFacingSleepApneaAlertChanged {
    eventType: Vital.ClientFacingSleepApneaAlertChangedEventType;
    userId: string;
    clientUserId: string;
    teamId: string;
    data: Vital.GroupedSleepApneaAlert;
}
