/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ClientFacingFloorsClimbedTimeseries {
    /** Deprecated */
    id?: number;
    /** Time zone UTC offset in seconds. Positive offset indicates east of UTC; negative offset indicates west of UTC; and null indicates the time zone information is unavailable at source. */
    timezoneOffset?: number;
    /** The reading type of the measurement. This is applicable only to Cholesterol, IGG, IGE and InsulinInjection. */
    type?: string;
    /** Measured in counts */
    unit: "count";
    /** The timestamp of the measurement. */
    timestamp: Date;
    /** Number of floors climbed at the time or interval::count */
    value: number;
}
