// This file was auto-generated by Fern from our API Definition.

export const ClientFacingStepsChangedEventType = {
    DailyDataStepsCreated: "daily.data.steps.created",
    DailyDataStepsUpdated: "daily.data.steps.updated",
} as const;
export type ClientFacingStepsChangedEventType =
    (typeof ClientFacingStepsChangedEventType)[keyof typeof ClientFacingStepsChangedEventType];
