// This file was auto-generated by Fern from our API Definition.

export const ClientFacingBodyMassIndexChangedEventType = {
    DailyDataBodyMassIndexCreated: "daily.data.body_mass_index.created",
    DailyDataBodyMassIndexUpdated: "daily.data.body_mass_index.updated",
} as const;
export type ClientFacingBodyMassIndexChangedEventType =
    (typeof ClientFacingBodyMassIndexChangedEventType)[keyof typeof ClientFacingBodyMassIndexChangedEventType];
