// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../index.js";

export interface ClientFacingBodyMassIndexChanged {
    eventType: Vital.ClientFacingBodyMassIndexChangedEventType;
    userId: string;
    clientUserId: string;
    teamId: string;
    data: Vital.GroupedBodyMassIndex;
}
