/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ClientFacingBloodOxygenTimeseries {
    id?: number;
    timezoneOffset?: number;
    type?: string;
    /** Measured in percentage (spo2). */
    unit: string;
    /** The timestamp of the measurement. */
    timestamp: Date;
    /** The value of the measurement. */
    value: number;
}
