// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../index.js";

export interface ClientFacingSleepStream {
    hrv?: Vital.ClientFacingHrvTimeseries[];
    heartrate?: Vital.ClientFacingHeartRateTimeseries[];
    hypnogram?: Vital.ClientFacingHypnogramTimeseries[];
    respiratoryRate?: Vital.ClientFacingRespiratoryRateTimeseries[];
}
