// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../index.js";

export interface ClientFacingRespiratoryRateHistoricalPullCompleted {
    eventType: "historical.data.respiratory_rate.created";
    userId: string;
    clientUserId: string;
    teamId: string;
    data: Vital.HistoricalPullCompleted;
}
