/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "../index";

export interface ClientFacingUvExposureChanged {
    eventType: Vital.ClientFacingUvExposureChangedEventType;
    userId: string;
    clientUserId: string;
    teamId: string;
    data: Vital.VitalCoreSchemasResponseSchemasTimeseriesClientFacingTimeseriesGroupClientFacingUvExposureSample;
}
