/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "../index";

export interface ClientFacingElectrocardiogram {
    id: string;
    sessionStart: Date;
    sessionEnd: Date;
    voltageSampleCount: number;
    heartRateMean?: number;
    samplingFrequencyHz?: number;
    classification?: Vital.ClientFacingElectrocardiogramClassification;
    inconclusiveCause?: Vital.ClientFacingElectrocardiogramInconclusiveCause;
    algorithmVersion?: string;
    timeZone?: string;
    sourceProvider: Vital.ClientFacingElectrocardiogramSourceProvider;
    sourceType: Vital.ClientFacingElectrocardiogramSourceType;
    sourceAppId?: string;
    sourceDeviceModel?: string;
    userId: string;
    source: Vital.ClientFacingSource;
}
