// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../index.js";

export interface ClientFacingInsurance {
    memberId: string;
    payorCode: string;
    relationship: Vital.ResponsibleRelationship;
    insured: Vital.VitalCoreSchemasDbSchemasLabTestInsurancePersonDetails;
    company: Vital.CompanyDetails;
    groupId?: string;
    guarantor?: Vital.GuarantorDetails;
}
