/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "../index";

export interface ConnectedSourceClientFacing {
    /** The provider of this connected source. */
    provider: Vital.ClientFacingProvider;
    /** When your item is created */
    createdOn: Date;
    /** Deprecated. Use `provider` instead. Subject to removal after 1 Jan 2024. */
    source: Vital.ClientFacingProvider;
}
