// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../index.js";

export interface ContinuousQueryTaskHistoryEntry {
    queryId: string;
    userId: string;
    status: Vital.ContinuousQueryTaskStatus;
    scheduledAt: Date;
    startedAt?: Date;
    endedAt?: Date;
    errorDetails?: string;
}
