/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "../index";

export interface ContraceptiveEntry {
    date: string;
    /** ℹ️ This enum is non-exhaustive. */
    type: Vital.ContraceptiveEntryType;
}
