// This file was auto-generated by Fern from our API Definition.

/** ℹ️ This enum is non-exhaustive. */
export const ContraceptiveEntryType = {
    Unspecified: "unspecified",
    Implant: "implant",
    Injection: "injection",
    Iud: "iud",
    IntravaginalRing: "intravaginal_ring",
    Oral: "oral",
    Patch: "patch",
} as const;
export type ContraceptiveEntryType = (typeof ContraceptiveEntryType)[keyof typeof ContraceptiveEntryType];
