// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../index.js";

export interface DatePartExpr {
    arg: Vital.DatePartExprArg;
    /** ℹ️ This enum is non-exhaustive. */
    datePart: Vital.DatePartExprDatePart;
}
