/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "../index";

export interface DateTruncExpr {
    dateTrunc: Vital.Period;
    arg: Vital.DateTruncExprArg;
}
