/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "../index";

export interface DatePartExpr {
    arg: Vital.DatePartExprArg;
    datePart: Vital.DatePartExprDatePart;
}
