/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type DiscreteTimeseriesExprField =
    | "source_provider"
    | "source_type"
    | "source_workout_id"
    | "source_sport"
    | "timezone_offset"
    | "type"
    | "value";

export const DiscreteTimeseriesExprField = {
    SourceProvider: "source_provider",
    SourceType: "source_type",
    SourceWorkoutId: "source_workout_id",
    SourceSport: "source_sport",
    TimezoneOffset: "timezone_offset",
    Type: "type",
    Value: "value",
} as const;
