/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EventDestinationPreferencesPreferred = "cloud_pubsub" | "rabbitmq" | "svix";

export const EventDestinationPreferencesPreferred = {
    CloudPubsub: "cloud_pubsub",
    Rabbitmq: "rabbitmq",
    Svix: "svix",
} as const;
