// This file was auto-generated by Fern from our API Definition.

/** ℹ️ This enum is non-exhaustive. */
export const GenderIdentity = {
    Male: "male",
    Female: "female",
    FemaleToMaleFtmTransgenderMaleTransMan: "female_to_male_ftm_transgender_male_trans_man",
    MaleToFemaleMtfTransgenderFemaleTransWoman: "male_to_female_mtf_transgender_female_trans_woman",
    Genderqueer: "genderqueer",
    Other: "other",
} as const;
export type GenderIdentity = (typeof GenderIdentity)[keyof typeof GenderIdentity];
