/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "../index";

export interface GroupedInhalerUsage {
    source: Vital.ClientFacingSource;
    data: Vital.ClientFacingInhalerUsageSample[];
}
