/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "../index";

export interface GroupedVo2Max {
    source: Vital.ClientFacingSource;
    data: Vital.ClientFacingVo2MaxTimeseries[];
}
