/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "../index";

export interface GuarantorDetails {
    firstName: string;
    lastName: string;
    address: Vital.VitalCoreSchemasDbSchemasLabTestInsuranceAddress;
    phoneNumber: string;
    householdIncome?: number;
    householdSize?: number;
    email?: string;
}
