/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * ℹ️ This enum is non-exhaustive.
 */
export type HomeProgesteroneTestEntryTestResult = "negative" | "positive" | "indeterminate";

export const HomeProgesteroneTestEntryTestResult = {
    Negative: "negative",
    Positive: "positive",
    Indeterminate: "indeterminate",
} as const;
