// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../index.js";

export interface IntervalTimeseriesExpr {
    /** ℹ️ This enum is non-exhaustive. */
    timeseries: Vital.IntervalTimeseriesExprTimeseries;
    /** ℹ️ This enum is non-exhaustive. */
    field: Vital.IntervalTimeseriesExprField;
}
