// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../index.js";

export interface LabReportResult {
    testName: string;
    value: string;
    type?: Vital.LabReportResultType;
    units?: string;
    maxReferenceRange?: number;
    minReferenceRange?: number;
    sourcePanelName?: string;
    loincMatches?: Vital.LoincMatch[];
    interpretation?: Vital.Interpretation;
    isAboveMaxRange?: boolean;
    isBelowMinRange?: boolean;
}
