// This file was auto-generated by Fern from our API Definition.

/** ℹ️ This enum is non-exhaustive. */
export const Labs = {
    Ayumetrix: "ayumetrix",
    Spiriplex: "spiriplex",
    Ussl: "ussl",
    Quest: "quest",
    Labcorp: "labcorp",
    Bioreference: "bioreference",
    UsBiotek: "us_biotek",
    Manual: "manual",
    Sanocardio: "sanocardio",
    Ihd: "ihd",
    Nexus: "nexus",
    MyUti: "my_uti",
} as const;
export type Labs = (typeof Labs)[keyof typeof Labs];
