/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The method used to perform a lab test.
 */
export type LabTestCollectionMethod = "testkit" | "walk_in_test" | "at_home_phlebotomy";

export const LabTestCollectionMethod = {
    Testkit: "testkit",
    WalkInTest: "walk_in_test",
    AtHomePhlebotomy: "at_home_phlebotomy",
} as const;
