// This file was auto-generated by Fern from our API Definition.

/** ℹ️ This enum is non-exhaustive. */
export const MarkerType = {
    Biomarker: "biomarker",
    Panel: "panel",
} as const;
export type MarkerType = (typeof MarkerType)[keyof typeof MarkerType];
