/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * ℹ️ This enum is non-exhaustive.
 */
export type MenstrualFlowEntryFlow = "unspecified" | "none" | "light" | "medium" | "heavy";

export const MenstrualFlowEntryFlow = {
    Unspecified: "unspecified",
    None: "none",
    Light: "light",
    Medium: "medium",
    Heavy: "heavy",
} as const;
