// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../index.js";

export interface MetricsResult {
    teamId: string;
    numberOfConnectedSources?: number;
    numberOfUsers?: number;
    numberOfErroredConnectedSources?: number;
    numberOfConnectedSourcesByWeek?: Vital.TimeseriesMetricPoint[];
    numberOfOrderedTests?: number;
}
