/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "../index";

export interface MissingBiomarkerResult {
    name: string;
    slug: string;
    reason: Vital.FailureType;
    loinc?: string;
    loincSlug?: string;
    providerId?: string;
}
