/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type OAuthProviders =
    | "oura"
    | "fitbit"
    | "garmin"
    | "strava"
    | "wahoo"
    | "ihealth"
    | "withings"
    | "google_fit"
    | "dexcom_v3"
    | "polar"
    | "cronometer"
    | "omron"
    | "whoop_v2";

export const OAuthProviders = {
    Oura: "oura",
    Fitbit: "fitbit",
    Garmin: "garmin",
    Strava: "strava",
    Wahoo: "wahoo",
    Ihealth: "ihealth",
    Withings: "withings",
    GoogleFit: "google_fit",
    DexcomV3: "dexcom_v3",
    Polar: "polar",
    Cronometer: "cronometer",
    Omron: "omron",
    WhoopV2: "whoop_v2",
} as const;
