/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "../index";

export interface OrderSetRequest {
    labTestIds?: string[];
    addOn?: Vital.AddOnOrder;
    labAccountId?: string;
}
