// This file was auto-generated by Fern from our API Definition.

/** ℹ️ This enum is non-exhaustive. */
export const OvulationTestEntryTestResult = {
    Negative: "negative",
    Positive: "positive",
    LuteinizingHormoneSurge: "luteinizing_hormone_surge",
    EstrogenSurge: "estrogen_surge",
    Indeterminate: "indeterminate",
} as const;
export type OvulationTestEntryTestResult =
    (typeof OvulationTestEntryTestResult)[keyof typeof OvulationTestEntryTestResult];
