/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PatientAddressCompatibleInput {
    receiverName?: string;
    street: string;
    streetNumber?: string;
    city: string;
    state: string;
    zip: string;
    country: string;
    phoneNumber?: string;
}
