/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PeriodUnit = "minute" | "hour" | "day" | "week" | "month" | "year";

export const PeriodUnit = {
    Minute: "minute",
    Hour: "hour",
    Day: "day",
    Week: "week",
    Month: "month",
    Year: "year",
} as const;
