// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../index.js";

export interface ProviderConnectionCreated {
    userId: string;
    /** Deprecated. Use `provider` instead. Subject to removal after 1 Jan 2024. */
    source: Vital.ClientFacingProvider;
    provider: Vital.ClientFacingProvider;
    /**
     * The unique identifier of the associated external data provider user.
     *
     * * OAuth Providers: User unique identifier; provider-specific formats
     * * Password Providers: Username
     * * Email Providers: Email
     * * Junction Mobile SDK Providers: `null` (not available)
     */
    externalUserId?: string;
    resourceAvailability: Record<string, Vital.ResourceAvailability>;
}
