/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * ℹ️ This enum is non-exhaustive.
 */
export type ProviderMfaRequestMethod = "sms" | "email";

export const ProviderMfaRequestMethod = {
    Sms: "sms",
    Email: "email",
} as const;
