/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An enumeration.
 */
export type Providers =
    | "oura"
    | "fitbit"
    | "garmin"
    | "whoop"
    | "strava"
    | "renpho"
    | "peloton"
    | "wahoo"
    | "zwift"
    | "freestyle_libre"
    | "freestyle_libre_ble"
    | "eight_sleep"
    | "withings"
    | "apple_health_kit"
    | "manual"
    | "ihealth"
    | "google_fit"
    | "beurer_api"
    | "beurer_ble"
    | "omron"
    | "omron_ble"
    | "onetouch_ble"
    | "accuchek_ble"
    | "contour_ble"
    | "dexcom"
    | "dexcom_v3"
    | "hammerhead"
    | "my_fitness_pal"
    | "health_connect"
    | "polar"
    | "cronometer"
    | "kardia";

export const Providers = {
    Oura: "oura",
    Fitbit: "fitbit",
    Garmin: "garmin",
    Whoop: "whoop",
    Strava: "strava",
    Renpho: "renpho",
    Peloton: "peloton",
    Wahoo: "wahoo",
    Zwift: "zwift",
    FreestyleLibre: "freestyle_libre",
    FreestyleLibreBle: "freestyle_libre_ble",
    EightSleep: "eight_sleep",
    Withings: "withings",
    AppleHealthKit: "apple_health_kit",
    Manual: "manual",
    Ihealth: "ihealth",
    GoogleFit: "google_fit",
    BeurerApi: "beurer_api",
    BeurerBle: "beurer_ble",
    Omron: "omron",
    OmronBle: "omron_ble",
    OnetouchBle: "onetouch_ble",
    AccuchekBle: "accuchek_ble",
    ContourBle: "contour_ble",
    Dexcom: "dexcom",
    DexcomV3: "dexcom_v3",
    Hammerhead: "hammerhead",
    MyFitnessPal: "my_fitness_pal",
    HealthConnect: "health_connect",
    Polar: "polar",
    Cronometer: "cronometer",
    Kardia: "kardia",
} as const;
