// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../index.js";

export interface PscAreaInfo {
    patientServiceCenters: Vital.PscAreaInfoDetails;
    supportedBillTypes: Vital.Billing[];
    labId: number;
}
