/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "../index";

export interface PscInfo {
    labId: number;
    slug: Vital.Labs;
    patientServiceCenters: Vital.ClientFacingLabLocation[];
}
