/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "..";

export interface QualificationItem {
    code: Vital.VitalCoreSchemasRequestSchemasOrdersCode;
    period: Vital.Period;
    identifier: Vital.IdentifierItem1[];
}
