/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "../index";

export type QuerySelectItem =
    | Vital.AggregateExpr
    | Vital.GroupKeyColumnExpr
    | Vital.SleepColumnExpr
    | Vital.ActivityColumnExpr
    | Vital.WorkoutColumnExpr
    | Vital.BodyColumnExpr
    | Vital.MealColumnExpr
    | Vital.ProfileColumnExpr
    | Vital.SleepScoreValueMacroExpr
    | Vital.ChronotypeValueMacroExpr
    | Vital.AsleepAtValueMacroExpr
    | Vital.AwakeAtValueMacroExpr
    | Vital.UnrecognizedValueMacroExpr
    | Vital.DiscreteTimeseriesExpr
    | Vital.IntervalTimeseriesExpr
    | Vital.BloodPressureTimeseriesExpr
    | Vital.TemperatureTimeseriesExpr
    | Vital.WorkoutDurationTimeseriesExpr
    | Vital.NoteTimeseriesExpr
    | Vital.IndexColumnExpr
    | Vital.SourceColumnExpr;
