// This file was auto-generated by Fern from our API Definition.

/** ℹ️ This enum is non-exhaustive. */
export const QuestionType = {
    Choice: "choice",
    Text: "text",
    Numeric: "numeric",
    MultiChoice: "multi_choice",
} as const;
export type QuestionType = (typeof QuestionType)[keyof typeof QuestionType];
