/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "..";

export interface Question {
    id: number;
    required: boolean;
    code: string;
    value: string;
    type: Vital.QuestionType;
    sequence: number;
    answers: Vital.Answer[];
}
