/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An enumeration.
 */
export type Region = "us" | "eu" | "sg" | "de" | "au" | "br" | "nl" | "fr";

export const Region = {
    Us: "us",
    Eu: "eu",
    Sg: "sg",
    De: "de",
    Au: "au",
    Br: "br",
    Nl: "nl",
    Fr: "fr",
} as const;
