/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "..";

export interface ResourceAvailability {
    status: Vital.Availability;
    scopeRequirements?: Vital.ScopeRequirementsGrants;
}
