/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "../index";

export interface SampleData {
    sampleId?: string;
    controlNumber?: string;
    dateCollected?: Vital.SampleDataDateCollected;
    dateReceived?: Vital.SampleDataDateReceived;
    dateReported?: Vital.SampleDataDateReported;
    performingLaboratories?: Record<string, Vital.PerformingLaboratory | undefined>;
    clinicalInformation?: Vital.ClinicalInformation;
}
