/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SexualOrientation =
    | "lesbian_gay_or_homosexual"
    | "heterosexual_or_straight"
    | "bisexual"
    | "dont_know"
    | "other";

export const SexualOrientation = {
    LesbianGayOrHomosexual: "lesbian_gay_or_homosexual",
    HeterosexualOrStraight: "heterosexual_or_straight",
    Bisexual: "bisexual",
    DontKnow: "dont_know",
    Other: "other",
} as const;
