/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "../index";

export interface SingleProviderHistoricalPullResponse {
    pulled: Record<string, Vital.SingleHistoricalPullStatistics>;
    notPulled: Vital.ClientFacingResource[];
}
