// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../index.js";

export interface SleepColumnExpr {
    /** ℹ️ This enum is non-exhaustive. */
    sleep: Vital.SleepColumnExprSleep;
}
