/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * ℹ️ This enum is non-exhaustive.
 */
export type SourceAuthType = "oauth" | "team_oauth" | "sdk" | "password" | "email" | "app" | "";

export const SourceAuthType = {
    Oauth: "oauth",
    TeamOauth: "team_oauth",
    Sdk: "sdk",
    Password: "password",
    Email: "email",
    App: "app",
    Empty: "",
} as const;
