/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SourceColumnExprSource =
    | "source_provider"
    | "source_type"
    | "source_app_id"
    | "source_workout_id"
    | "source_sport";

export const SourceColumnExprSource = {
    SourceProvider: "source_provider",
    SourceType: "source_type",
    SourceAppId: "source_app_id",
    SourceWorkoutId: "source_workout_id",
    SourceSport: "source_sport",
} as const;
