/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TimeSlot {
    bookingKey?: string;
    /** Time is in UTC */
    start: string;
    /** Time is in UTC */
    end: string;
    expiresAt?: string;
    price: number;
    isPriority: boolean;
    numAppointmentsAvailable: number;
}
