/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface VitalCoreSchemasRequestSchemasOrdersCodingItem {
    system: string;
    code: string;
    display?: string;
}
