/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "../index";

export interface VitalCoreSchemasResponseSchemasTimeseriesClientFacingTimeseriesGroupClientFacingStandDurationSample {
    source: Vital.ClientFacingSource;
    data: Vital.ClientFacingStandDurationSample[];
}
