/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "../index";

export interface VitalCoreSchemasResponseSchemasTimeseriesClientFacingTimeseriesGroupClientFacingHeartRateAlertSample {
    source: Vital.ClientFacingSource;
    data: Vital.ClientFacingHeartRateAlertSample[];
}
