/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vital from "../index";

export interface VitalCoreSchemasDbSchemasLabTestHealthInsurancePersonDetails {
    firstName: string;
    lastName: string;
    address: Vital.VitalCoreSchemasDbSchemasLabTestHealthInsuranceAddress;
    phoneNumber: string;
    phoneType?: string;
}
