/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Vital from "../../../../api/index";
import * as core from "../../../../core";

export const LinkBulkPauseRequestTeamId: core.serialization.Schema<
    serializers.LinkBulkPauseRequestTeamId.Raw,
    Vital.LinkBulkPauseRequestTeamId
> = core.serialization.enum_(["infer_from_context"]);

export declare namespace LinkBulkPauseRequestTeamId {
    type Raw = "infer_from_context";
}
