/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Vital from "../../../../api/index";
import * as core from "../../../../core";

export const ListBulkOpsLinkRequestTeamId: core.serialization.Schema<
    serializers.ListBulkOpsLinkRequestTeamId.Raw,
    Vital.ListBulkOpsLinkRequestTeamId
> = core.serialization.enum_(["infer_from_context"]);

export declare namespace ListBulkOpsLinkRequestTeamId {
    type Raw = "infer_from_context";
}
