// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../../../index.js";

/**
 * @example
 *     {
 *         sampleId: "sample_id",
 *         patientDetails: {
 *             firstName: "first_name",
 *             lastName: "last_name",
 *             dob: "dob",
 *             gender: "female",
 *             phoneNumber: "phone_number",
 *             email: "email"
 *         },
 *         patientAddress: {
 *             firstLine: "first_line",
 *             city: "city",
 *             state: "state",
 *             zip: "zip",
 *             country: "country"
 *         }
 *     }
 */
export interface RegisterTestkitRequest {
    /** The user ID of the patient. */
    userId?: string;
    sampleId: string;
    patientDetails: Vital.PatientDetailsWithValidation;
    patientAddress: Vital.PatientAddressWithValidation;
    physician?: Vital.PhysicianCreateRequestBase;
    healthInsurance?: Vital.HealthInsuranceCreateRequest;
    consents?: Vital.Consent[];
}
