/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";

export const AggregationResult: core.serialization.ObjectSchema<
    serializers.AggregationResult.Raw,
    Vital.AggregationResult
> = core.serialization.object({
    table: core.serialization.record(
        core.serialization.string(),
        core.serialization.list(core.serialization.unknown())
    ),
});

export declare namespace AggregationResult {
    interface Raw {
        table: Record<string, unknown[]>;
    }
}
