/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";
import { AggregateExprArg } from "./AggregateExprArg";
import { AggregateExprFunc } from "./AggregateExprFunc";

export const AggregateExpr: core.serialization.ObjectSchema<serializers.AggregateExpr.Raw, Vital.AggregateExpr> =
    core.serialization.object({
        arg: AggregateExprArg,
        func: AggregateExprFunc,
    });

export declare namespace AggregateExpr {
    interface Raw {
        arg: AggregateExprArg.Raw;
        func: AggregateExprFunc.Raw;
    }
}
