// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ActivityColumnExpr } from "./ActivityColumnExpr.js";
import { AsleepAtValueMacroExpr } from "./AsleepAtValueMacroExpr.js";
import { AwakeAtValueMacroExpr } from "./AwakeAtValueMacroExpr.js";
import { BloodPressureTimeseriesExpr } from "./BloodPressureTimeseriesExpr.js";
import { BodyColumnExpr } from "./BodyColumnExpr.js";
import { ChronotypeValueMacroExpr } from "./ChronotypeValueMacroExpr.js";
import { DiscreteTimeseriesExpr } from "./DiscreteTimeseriesExpr.js";
import { IndexColumnExpr } from "./IndexColumnExpr.js";
import { IntervalTimeseriesExpr } from "./IntervalTimeseriesExpr.js";
import { MealColumnExpr } from "./MealColumnExpr.js";
import { NoteTimeseriesExpr } from "./NoteTimeseriesExpr.js";
import { ProfileColumnExpr } from "./ProfileColumnExpr.js";
import { SleepColumnExpr } from "./SleepColumnExpr.js";
import { SleepScoreValueMacroExpr } from "./SleepScoreValueMacroExpr.js";
import { TemperatureTimeseriesExpr } from "./TemperatureTimeseriesExpr.js";
import { UnrecognizedValueMacroExpr } from "./UnrecognizedValueMacroExpr.js";
import { WorkoutColumnExpr } from "./WorkoutColumnExpr.js";
import { WorkoutDurationTimeseriesExpr } from "./WorkoutDurationTimeseriesExpr.js";

export const AggregateExprArg: core.serialization.Schema<serializers.AggregateExprArg.Raw, Vital.AggregateExprArg> =
    core.serialization.undiscriminatedUnion([
        SleepColumnExpr,
        ActivityColumnExpr,
        WorkoutColumnExpr,
        BodyColumnExpr,
        MealColumnExpr,
        ProfileColumnExpr,
        SleepScoreValueMacroExpr,
        ChronotypeValueMacroExpr,
        AsleepAtValueMacroExpr,
        AwakeAtValueMacroExpr,
        UnrecognizedValueMacroExpr,
        DiscreteTimeseriesExpr,
        IntervalTimeseriesExpr,
        BloodPressureTimeseriesExpr,
        TemperatureTimeseriesExpr,
        WorkoutDurationTimeseriesExpr,
        NoteTimeseriesExpr,
        IndexColumnExpr,
    ]);

export declare namespace AggregateExprArg {
    export type Raw =
        | SleepColumnExpr.Raw
        | ActivityColumnExpr.Raw
        | WorkoutColumnExpr.Raw
        | BodyColumnExpr.Raw
        | MealColumnExpr.Raw
        | ProfileColumnExpr.Raw
        | SleepScoreValueMacroExpr.Raw
        | ChronotypeValueMacroExpr.Raw
        | AsleepAtValueMacroExpr.Raw
        | AwakeAtValueMacroExpr.Raw
        | UnrecognizedValueMacroExpr.Raw
        | DiscreteTimeseriesExpr.Raw
        | IntervalTimeseriesExpr.Raw
        | BloodPressureTimeseriesExpr.Raw
        | TemperatureTimeseriesExpr.Raw
        | WorkoutDurationTimeseriesExpr.Raw
        | NoteTimeseriesExpr.Raw
        | IndexColumnExpr.Raw;
}
