// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AoEAnswer: core.serialization.ObjectSchema<serializers.AoEAnswer.Raw, Vital.AoEAnswer> =
    core.serialization.object({
        markerId: core.serialization.property("marker_id", core.serialization.number()),
        questionId: core.serialization.property("question_id", core.serialization.number()),
        answer: core.serialization.string(),
    });

export declare namespace AoEAnswer {
    export interface Raw {
        marker_id: number;
        question_id: number;
        answer: string;
    }
}
