/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vital from "../../api";
import * as core from "../../core";

export const AppointmentType: core.serialization.Schema<serializers.AppointmentType.Raw, Vital.AppointmentType> =
    core.serialization.stringLiteral("phlebotomy");

export declare namespace AppointmentType {
    type Raw = "phlebotomy";
}
