// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AuthType: core.serialization.Schema<serializers.AuthType.Raw, Vital.AuthType> = core.serialization.enum_([
    "password",
    "oauth",
    "email",
]);

export declare namespace AuthType {
    export type Raw = "password" | "oauth" | "email";
}
