/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vital from "../../api";
import * as core from "../../core";

export const Beneficiary: core.serialization.ObjectSchema<serializers.Beneficiary.Raw, Vital.Beneficiary> =
    core.serialization.object({
        reference: core.serialization.string(),
    });

export declare namespace Beneficiary {
    interface Raw {
        reference: string;
    }
}
