// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { BloodPressureTimeseriesExprField } from "./BloodPressureTimeseriesExprField.js";

export const BloodPressureTimeseriesExpr: core.serialization.ObjectSchema<
    serializers.BloodPressureTimeseriesExpr.Raw,
    Vital.BloodPressureTimeseriesExpr
> = core.serialization.object({
    timeseries: core.serialization.stringLiteral("blood_pressure"),
    field: BloodPressureTimeseriesExprField,
});

export declare namespace BloodPressureTimeseriesExpr {
    export interface Raw {
        timeseries: "blood_pressure";
        field: BloodPressureTimeseriesExprField.Raw;
    }
}
