/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";
import { ClientFacingProvider } from "./ClientFacingProvider";

export const BodyV2InDb: core.serialization.ObjectSchema<serializers.BodyV2InDb.Raw, Vital.BodyV2InDb> =
    core.serialization.object({
        timestamp: core.serialization.date(),
        data: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
        providerId: core.serialization.property("provider_id", core.serialization.string()),
        userId: core.serialization.property("user_id", core.serialization.string()),
        sourceId: core.serialization.property("source_id", core.serialization.number()),
        priorityId: core.serialization.property("priority_id", core.serialization.number().optional()),
        id: core.serialization.string(),
        source: ClientFacingProvider.optional(),
        priority: core.serialization.number().optional(),
        createdAt: core.serialization.property("created_at", core.serialization.date().optional()),
        updatedAt: core.serialization.property("updated_at", core.serialization.date().optional()),
    });

export declare namespace BodyV2InDb {
    interface Raw {
        timestamp: string;
        data: Record<string, unknown>;
        provider_id: string;
        user_id: string;
        source_id: number;
        priority_id?: number | null;
        id: string;
        source?: ClientFacingProvider.Raw | null;
        priority?: number | null;
        created_at?: string | null;
        updated_at?: string | null;
    }
}
