/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";
import { OAuthProviders } from "./OAuthProviders";

export const BulkPauseConnectionsBody: core.serialization.ObjectSchema<
    serializers.BulkPauseConnectionsBody.Raw,
    Vital.BulkPauseConnectionsBody
> = core.serialization.object({
    userIds: core.serialization.property("user_ids", core.serialization.list(core.serialization.string())),
    provider: OAuthProviders,
});

export declare namespace BulkPauseConnectionsBody {
    interface Raw {
        user_ids: string[];
        provider: OAuthProviders.Raw;
    }
}
