/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";

export const BulkOpType: core.serialization.Schema<serializers.BulkOpType.Raw, Vital.BulkOpType> =
    core.serialization.enum_(["link_bulk_import", "link_bulk_historical_trigger"]);

export declare namespace BulkOpType {
    type Raw = "link_bulk_import" | "link_bulk_historical_trigger";
}
