// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const CervicalMucusEntryQuality: core.serialization.Schema<
    serializers.CervicalMucusEntryQuality.Raw,
    Vital.CervicalMucusEntryQuality
> = core.serialization.enum_(["dry", "sticky", "creamy", "watery", "egg_white"]);

export declare namespace CervicalMucusEntryQuality {
    export type Raw = "dry" | "sticky" | "creamy" | "watery" | "egg_white";
}
