// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { LabTestCollectionMethod } from "./LabTestCollectionMethod.js";
import { LabTestSampleType } from "./LabTestSampleType.js";

export const ClientFacingLab: core.serialization.ObjectSchema<serializers.ClientFacingLab.Raw, Vital.ClientFacingLab> =
    core.serialization.object({
        id: core.serialization.number(),
        slug: core.serialization.string(),
        name: core.serialization.string(),
        firstLineAddress: core.serialization.property("first_line_address", core.serialization.string()),
        city: core.serialization.string(),
        zipcode: core.serialization.string(),
        collectionMethods: core.serialization.property(
            "collection_methods",
            core.serialization.list(LabTestCollectionMethod),
        ),
        sampleTypes: core.serialization.property("sample_types", core.serialization.list(LabTestSampleType)),
    });

export declare namespace ClientFacingLab {
    export interface Raw {
        id: number;
        slug: string;
        name: string;
        first_line_address: string;
        city: string;
        zipcode: string;
        collection_methods: LabTestCollectionMethod.Raw[];
        sample_types: LabTestSampleType.Raw[];
    }
}
