/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";

export const ClientFacingSleepCycleChangedEventType: core.serialization.Schema<
    serializers.ClientFacingSleepCycleChangedEventType.Raw,
    Vital.ClientFacingSleepCycleChangedEventType
> = core.serialization.enum_(["daily.data.sleep_cycle.created", "daily.data.sleep_cycle.updated"]);

export declare namespace ClientFacingSleepCycleChangedEventType {
    type Raw = "daily.data.sleep_cycle.created" | "daily.data.sleep_cycle.updated";
}
