// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { HistoricalPullCompleted } from "./HistoricalPullCompleted.js";

export const ClientFacingVo2MaxHistoricalPullCompleted: core.serialization.ObjectSchema<
    serializers.ClientFacingVo2MaxHistoricalPullCompleted.Raw,
    Vital.ClientFacingVo2MaxHistoricalPullCompleted
> = core.serialization.object({
    eventType: core.serialization.property(
        "event_type",
        core.serialization.stringLiteral("historical.data.vo2_max.created"),
    ),
    userId: core.serialization.property("user_id", core.serialization.string()),
    clientUserId: core.serialization.property("client_user_id", core.serialization.string()),
    teamId: core.serialization.property("team_id", core.serialization.string()),
    data: HistoricalPullCompleted,
});

export declare namespace ClientFacingVo2MaxHistoricalPullCompleted {
    export interface Raw {
        event_type: "historical.data.vo2_max.created";
        user_id: string;
        client_user_id: string;
        team_id: string;
        data: HistoricalPullCompleted.Raw;
    }
}
