// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ClientFacingAtHomePhlebotomyOrderDetails } from "./ClientFacingAtHomePhlebotomyOrderDetails.js";
import { ClientFacingOnSiteCollectionOrderDetails } from "./ClientFacingOnSiteCollectionOrderDetails.js";
import { ClientFacingTestKitOrderDetails } from "./ClientFacingTestKitOrderDetails.js";
import { ClientFacingWalkInOrderDetails } from "./ClientFacingWalkInOrderDetails.js";

export const ClientFacingOrderDetails: core.serialization.Schema<
    serializers.ClientFacingOrderDetails.Raw,
    Vital.ClientFacingOrderDetails
> = core.serialization
    .union("type", {
        walk_in_test: ClientFacingWalkInOrderDetails,
        testkit: ClientFacingTestKitOrderDetails,
        at_home_phlebotomy: ClientFacingAtHomePhlebotomyOrderDetails,
        on_site_collection: ClientFacingOnSiteCollectionOrderDetails,
    })
    .transform<Vital.ClientFacingOrderDetails>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace ClientFacingOrderDetails {
    export type Raw =
        | ClientFacingOrderDetails.WalkInTest
        | ClientFacingOrderDetails.Testkit
        | ClientFacingOrderDetails.AtHomePhlebotomy
        | ClientFacingOrderDetails.OnSiteCollection;

    export interface WalkInTest extends ClientFacingWalkInOrderDetails.Raw {
        type: "walk_in_test";
    }

    export interface Testkit extends ClientFacingTestKitOrderDetails.Raw {
        type: "testkit";
    }

    export interface AtHomePhlebotomy extends ClientFacingAtHomePhlebotomyOrderDetails.Raw {
        type: "at_home_phlebotomy";
    }

    export interface OnSiteCollection extends ClientFacingOnSiteCollectionOrderDetails.Raw {
        type: "on_site_collection";
    }
}
