/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";

export const ClientFacingForcedVitalCapacityChangedEventType: core.serialization.Schema<
    serializers.ClientFacingForcedVitalCapacityChangedEventType.Raw,
    Vital.ClientFacingForcedVitalCapacityChangedEventType
> = core.serialization.enum_(["daily.data.forced_vital_capacity.created", "daily.data.forced_vital_capacity.updated"]);

export declare namespace ClientFacingForcedVitalCapacityChangedEventType {
    type Raw = "daily.data.forced_vital_capacity.created" | "daily.data.forced_vital_capacity.updated";
}
