// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ClientFacingStandHourSampleType: core.serialization.Schema<
    serializers.ClientFacingStandHourSampleType.Raw,
    Vital.ClientFacingStandHourSampleType
> = core.serialization.enum_(["stood", "idle"]);

export declare namespace ClientFacingStandHourSampleType {
    export type Raw = "stood" | "idle";
}
