/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vital from "../../api";
import * as core from "../../core";

export const ClientFacingProviderWithStatus: core.serialization.ObjectSchema<
    serializers.ClientFacingProviderWithStatus.Raw,
    Vital.ClientFacingProviderWithStatus
> = core.serialization.object({
    name: core.serialization.string(),
    slug: core.serialization.string(),
    logo: core.serialization.string(),
    status: core.serialization.string(),
});

export declare namespace ClientFacingProviderWithStatus {
    interface Raw {
        name: string;
        slug: string;
        logo: string;
        status: string;
    }
}
