// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ClientFacingFloorsClimbedChangedEventType: core.serialization.Schema<
    serializers.ClientFacingFloorsClimbedChangedEventType.Raw,
    Vital.ClientFacingFloorsClimbedChangedEventType
> = core.serialization.enum_(["daily.data.floors_climbed.created", "daily.data.floors_climbed.updated"]);

export declare namespace ClientFacingFloorsClimbedChangedEventType {
    export type Raw = "daily.data.floors_climbed.created" | "daily.data.floors_climbed.updated";
}
