// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ClientFacingStreamDistance: core.serialization.Schema<
    serializers.ClientFacingStreamDistance.Raw,
    Vital.ClientFacingStreamDistance
> = core.serialization.undiscriminatedUnion([
    core.serialization.list(core.serialization.number().optional()),
    core.serialization.list(core.serialization.number()),
]);

export declare namespace ClientFacingStreamDistance {
    export type Raw = (number | null | undefined)[] | number[];
}
