// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ClientFacingCholesterolChangedEventType } from "./ClientFacingCholesterolChangedEventType.js";
import { GroupedCholesterol } from "./GroupedCholesterol.js";

export const ClientFacingCholesterolChanged: core.serialization.ObjectSchema<
    serializers.ClientFacingCholesterolChanged.Raw,
    Vital.ClientFacingCholesterolChanged
> = core.serialization.object({
    eventType: core.serialization.property("event_type", ClientFacingCholesterolChangedEventType),
    userId: core.serialization.property("user_id", core.serialization.string()),
    clientUserId: core.serialization.property("client_user_id", core.serialization.string()),
    teamId: core.serialization.property("team_id", core.serialization.string()),
    data: GroupedCholesterol,
});

export declare namespace ClientFacingCholesterolChanged {
    export interface Raw {
        event_type: ClientFacingCholesterolChangedEventType.Raw;
        user_id: string;
        client_user_id: string;
        team_id: string;
        data: GroupedCholesterol.Raw;
    }
}
