/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vital from "../../api";
import * as core from "../../core";
import { LabLocationMetadata } from "./LabLocationMetadata";

export const ClientFacingLabLocation: core.serialization.ObjectSchema<
    serializers.ClientFacingLabLocation.Raw,
    Vital.ClientFacingLabLocation
> = core.serialization.object({
    metadata: LabLocationMetadata,
    distance: core.serialization.number(),
});

export declare namespace ClientFacingLabLocation {
    interface Raw {
        metadata: LabLocationMetadata.Raw;
        distance: number;
    }
}
