// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ClientFacingBodyFatTimeseries: core.serialization.ObjectSchema<
    serializers.ClientFacingBodyFatTimeseries.Raw,
    Vital.ClientFacingBodyFatTimeseries
> = core.serialization.object({
    id: core.serialization.number().optional(),
    timezoneOffset: core.serialization.property("timezone_offset", core.serialization.number().optional()),
    type: core.serialization.string().optional(),
    unit: core.serialization.string(),
    timestamp: core.serialization.date(),
    value: core.serialization.number(),
});

export declare namespace ClientFacingBodyFatTimeseries {
    export interface Raw {
        id?: number | null;
        timezone_offset?: number | null;
        type?: string | null;
        unit: string;
        timestamp: string;
        value: number;
    }
}
