/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";
import { ClientFacingWorkoutsChangedEventType } from "./ClientFacingWorkoutsChangedEventType";
import { ClientFacingWorkout } from "./ClientFacingWorkout";

export const ClientFacingWorkoutsChanged: core.serialization.ObjectSchema<
    serializers.ClientFacingWorkoutsChanged.Raw,
    Vital.ClientFacingWorkoutsChanged
> = core.serialization.object({
    eventType: core.serialization.property("event_type", ClientFacingWorkoutsChangedEventType),
    userId: core.serialization.property("user_id", core.serialization.string()),
    clientUserId: core.serialization.property("client_user_id", core.serialization.string()),
    teamId: core.serialization.property("team_id", core.serialization.string()),
    data: ClientFacingWorkout,
});

export declare namespace ClientFacingWorkoutsChanged {
    interface Raw {
        event_type: ClientFacingWorkoutsChangedEventType.Raw;
        user_id: string;
        client_user_id: string;
        team_id: string;
        data: ClientFacingWorkout.Raw;
    }
}
