/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";
import { ClientFacingSource } from "./ClientFacingSource";

export const ClientFacingBody: core.serialization.ObjectSchema<
    serializers.ClientFacingBody.Raw,
    Vital.ClientFacingBody
> = core.serialization.object({
    userId: core.serialization.property("user_id", core.serialization.string()),
    id: core.serialization.string(),
    date: core.serialization.date(),
    calendarDate: core.serialization.property("calendar_date", core.serialization.string()),
    weight: core.serialization.number().optional(),
    fat: core.serialization.number().optional(),
    waterPercentage: core.serialization.property("water_percentage", core.serialization.number().optional()),
    muscleMassPercentage: core.serialization.property("muscle_mass_percentage", core.serialization.number().optional()),
    visceralFatIndex: core.serialization.property("visceral_fat_index", core.serialization.number().optional()),
    boneMassPercentage: core.serialization.property("bone_mass_percentage", core.serialization.number().optional()),
    bodyMassIndex: core.serialization.property("body_mass_index", core.serialization.number().optional()),
    leanBodyMassKilogram: core.serialization.property(
        "lean_body_mass_kilogram",
        core.serialization.number().optional()
    ),
    waistCircumferenceCentimeter: core.serialization.property(
        "waist_circumference_centimeter",
        core.serialization.number().optional()
    ),
    source: ClientFacingSource,
});

export declare namespace ClientFacingBody {
    interface Raw {
        user_id: string;
        id: string;
        date: string;
        calendar_date: string;
        weight?: number | null;
        fat?: number | null;
        water_percentage?: number | null;
        muscle_mass_percentage?: number | null;
        visceral_fat_index?: number | null;
        bone_mass_percentage?: number | null;
        body_mass_index?: number | null;
        lean_body_mass_kilogram?: number | null;
        waist_circumference_centimeter?: number | null;
        source: ClientFacingSource.Raw;
    }
}
