/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";
import { ClientFacingConnectionErrorDetailsErrorType } from "./ClientFacingConnectionErrorDetailsErrorType";

export const ClientFacingConnectionErrorDetails: core.serialization.ObjectSchema<
    serializers.ClientFacingConnectionErrorDetails.Raw,
    Vital.ClientFacingConnectionErrorDetails
> = core.serialization.object({
    errorType: core.serialization.property("error_type", ClientFacingConnectionErrorDetailsErrorType),
    errorMessage: core.serialization.property("error_message", core.serialization.string()),
    erroredAt: core.serialization.property("errored_at", core.serialization.string()),
});

export declare namespace ClientFacingConnectionErrorDetails {
    interface Raw {
        error_type: ClientFacingConnectionErrorDetailsErrorType.Raw;
        error_message: string;
        errored_at: string;
    }
}
