// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ClientFacingAtHomePhlebotomyOrder } from "./ClientFacingAtHomePhlebotomyOrder.js";

export const ClientFacingAtHomePhlebotomyOrderDetails: core.serialization.ObjectSchema<
    serializers.ClientFacingAtHomePhlebotomyOrderDetails.Raw,
    Vital.ClientFacingAtHomePhlebotomyOrderDetails
> = core.serialization.object({
    data: ClientFacingAtHomePhlebotomyOrder.optional(),
});

export declare namespace ClientFacingAtHomePhlebotomyOrderDetails {
    export interface Raw {
        data?: ClientFacingAtHomePhlebotomyOrder.Raw | null;
    }
}
