// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ClientFacingCaffeineChangedEventType } from "./ClientFacingCaffeineChangedEventType.js";
import { GroupedCaffeine } from "./GroupedCaffeine.js";

export const ClientFacingCaffeineChanged: core.serialization.ObjectSchema<
    serializers.ClientFacingCaffeineChanged.Raw,
    Vital.ClientFacingCaffeineChanged
> = core.serialization.object({
    eventType: core.serialization.property("event_type", ClientFacingCaffeineChangedEventType),
    userId: core.serialization.property("user_id", core.serialization.string()),
    clientUserId: core.serialization.property("client_user_id", core.serialization.string()),
    teamId: core.serialization.property("team_id", core.serialization.string()),
    data: GroupedCaffeine,
});

export declare namespace ClientFacingCaffeineChanged {
    export interface Raw {
        event_type: ClientFacingCaffeineChangedEventType.Raw;
        user_id: string;
        client_user_id: string;
        team_id: string;
        data: GroupedCaffeine.Raw;
    }
}
