/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";
import { ClientFacingSource } from "./ClientFacingSource";
import { ClientFacingWorkoutDurationSample } from "./ClientFacingWorkoutDurationSample";

export const ClientFacingTimeseriesGroupClientFacingWorkoutDurationSample: core.serialization.ObjectSchema<
    serializers.ClientFacingTimeseriesGroupClientFacingWorkoutDurationSample.Raw,
    Vital.ClientFacingTimeseriesGroupClientFacingWorkoutDurationSample
> = core.serialization.object({
    source: ClientFacingSource,
    data: core.serialization.list(ClientFacingWorkoutDurationSample),
});

export declare namespace ClientFacingTimeseriesGroupClientFacingWorkoutDurationSample {
    interface Raw {
        source: ClientFacingSource.Raw;
        data: ClientFacingWorkoutDurationSample.Raw[];
    }
}
