// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ClientFacingAppointmentChangedEventType: core.serialization.Schema<
    serializers.ClientFacingAppointmentChangedEventType.Raw,
    Vital.ClientFacingAppointmentChangedEventType
> = core.serialization.enum_(["labtest.appointment.created", "labtest.appointment.updated"]);

export declare namespace ClientFacingAppointmentChangedEventType {
    export type Raw = "labtest.appointment.created" | "labtest.appointment.updated";
}
