/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vital from "../../api";
import * as core from "../../core";

export const ClientFacingWalkInOrderDetails: core.serialization.ObjectSchema<
    serializers.ClientFacingWalkInOrderDetails.Raw,
    Vital.ClientFacingWalkInOrderDetails
> = core.serialization.object({
    data: core.serialization.lazyObject(async () => (await import("..")).ClientFacingWalkInTestOrder).optional(),
});

export declare namespace ClientFacingWalkInOrderDetails {
    interface Raw {
        data?: serializers.ClientFacingWalkInTestOrder.Raw | null;
    }
}
