/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";
import { OrderStatus } from "./OrderStatus";

export const ClientFacingOrderEvent: core.serialization.ObjectSchema<
    serializers.ClientFacingOrderEvent.Raw,
    Vital.ClientFacingOrderEvent
> = core.serialization.object({
    id: core.serialization.number(),
    createdAt: core.serialization.property("created_at", core.serialization.date()),
    status: OrderStatus,
});

export declare namespace ClientFacingOrderEvent {
    interface Raw {
        id: number;
        created_at: string;
        status: OrderStatus.Raw;
    }
}
