/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";

export const ClientFacingStandHourSampleType: core.serialization.Schema<
    serializers.ClientFacingStandHourSampleType.Raw,
    Vital.ClientFacingStandHourSampleType
> = core.serialization.enum_(["stood", "idle"]);

export declare namespace ClientFacingStandHourSampleType {
    type Raw = "stood" | "idle";
}
