/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vital from "../../api";
import * as core from "../../core";

export const ClientFacingBody: core.serialization.ObjectSchema<
    serializers.ClientFacingBody.Raw,
    Vital.ClientFacingBody
> = core.serialization.object({
    userId: core.serialization.property("user_id", core.serialization.string()),
    id: core.serialization.string(),
    date: core.serialization.date(),
    calendarDate: core.serialization.property("calendar_date", core.serialization.string()),
    weight: core.serialization.number().optional(),
    fat: core.serialization.number().optional(),
    source: core.serialization.lazyObject(async () => (await import("..")).ClientFacingSource),
});

export declare namespace ClientFacingBody {
    interface Raw {
        user_id: string;
        id: string;
        date: string;
        calendar_date: string;
        weight?: number | null;
        fat?: number | null;
        source: serializers.ClientFacingSource.Raw;
    }
}
