/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";
import { ClientFacingInsulinInjectionChangedEventType } from "./ClientFacingInsulinInjectionChangedEventType";
import { GroupedInsulinInjection } from "./GroupedInsulinInjection";

export const ClientFacingInsulinInjectionChanged: core.serialization.ObjectSchema<
    serializers.ClientFacingInsulinInjectionChanged.Raw,
    Vital.ClientFacingInsulinInjectionChanged
> = core.serialization.object({
    eventType: core.serialization.property("event_type", ClientFacingInsulinInjectionChangedEventType),
    userId: core.serialization.property("user_id", core.serialization.string()),
    clientUserId: core.serialization.property("client_user_id", core.serialization.string()),
    teamId: core.serialization.property("team_id", core.serialization.string()),
    data: GroupedInsulinInjection,
});

export declare namespace ClientFacingInsulinInjectionChanged {
    interface Raw {
        event_type: ClientFacingInsulinInjectionChangedEventType.Raw;
        user_id: string;
        client_user_id: string;
        team_id: string;
        data: GroupedInsulinInjection.Raw;
    }
}
