// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ClientFacingBodyTemperatureDeltaChangedEventType: core.serialization.Schema<
    serializers.ClientFacingBodyTemperatureDeltaChangedEventType.Raw,
    Vital.ClientFacingBodyTemperatureDeltaChangedEventType
> = core.serialization.enum_([
    "daily.data.body_temperature_delta.created",
    "daily.data.body_temperature_delta.updated",
]);

export declare namespace ClientFacingBodyTemperatureDeltaChangedEventType {
    export type Raw = "daily.data.body_temperature_delta.created" | "daily.data.body_temperature_delta.updated";
}
