// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ContinuousQueryResultTableChanges } from "./ContinuousQueryResultTableChanges.js";

export const ClientFacingContinuousQueryResultTableChanged: core.serialization.ObjectSchema<
    serializers.ClientFacingContinuousQueryResultTableChanged.Raw,
    Vital.ClientFacingContinuousQueryResultTableChanged
> = core.serialization.object({
    eventType: core.serialization.property(
        "event_type",
        core.serialization.stringLiteral("continuous_query.result_table.changed"),
    ),
    userId: core.serialization.property("user_id", core.serialization.string()),
    clientUserId: core.serialization.property("client_user_id", core.serialization.string()),
    teamId: core.serialization.property("team_id", core.serialization.string()),
    data: core.serialization.list(ContinuousQueryResultTableChanges),
});

export declare namespace ClientFacingContinuousQueryResultTableChanged {
    export interface Raw {
        event_type: "continuous_query.result_table.changed";
        user_id: string;
        client_user_id: string;
        team_id: string;
        data: ContinuousQueryResultTableChanges.Raw[];
    }
}
