/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";

export const ClientFacingInsulinInjectionSampleType: core.serialization.Schema<
    serializers.ClientFacingInsulinInjectionSampleType.Raw,
    Vital.ClientFacingInsulinInjectionSampleType
> = core.serialization.enum_(["rapid_acting", "long_acting"]);

export declare namespace ClientFacingInsulinInjectionSampleType {
    type Raw = "rapid_acting" | "long_acting";
}
