/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";

export const ClientFacingBodyMassIndexChangedEventType: core.serialization.Schema<
    serializers.ClientFacingBodyMassIndexChangedEventType.Raw,
    Vital.ClientFacingBodyMassIndexChangedEventType
> = core.serialization.enum_(["daily.data.body_mass_index.created", "daily.data.body_mass_index.updated"]);

export declare namespace ClientFacingBodyMassIndexChangedEventType {
    type Raw = "daily.data.body_mass_index.created" | "daily.data.body_mass_index.updated";
}
