/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";
import { ClientFacingForcedVitalCapacityChangedEventType } from "./ClientFacingForcedVitalCapacityChangedEventType";
import { VitalCoreSchemasResponseSchemasTimeseriesClientFacingTimeseriesGroupClientFacingForcedVitalCapacitySample } from "./VitalCoreSchemasResponseSchemasTimeseriesClientFacingTimeseriesGroupClientFacingForcedVitalCapacitySample";

export const ClientFacingForcedVitalCapacityChanged: core.serialization.ObjectSchema<
    serializers.ClientFacingForcedVitalCapacityChanged.Raw,
    Vital.ClientFacingForcedVitalCapacityChanged
> = core.serialization.object({
    eventType: core.serialization.property("event_type", ClientFacingForcedVitalCapacityChangedEventType),
    userId: core.serialization.property("user_id", core.serialization.string()),
    clientUserId: core.serialization.property("client_user_id", core.serialization.string()),
    teamId: core.serialization.property("team_id", core.serialization.string()),
    data: VitalCoreSchemasResponseSchemasTimeseriesClientFacingTimeseriesGroupClientFacingForcedVitalCapacitySample,
});

export declare namespace ClientFacingForcedVitalCapacityChanged {
    interface Raw {
        event_type: ClientFacingForcedVitalCapacityChangedEventType.Raw;
        user_id: string;
        client_user_id: string;
        team_id: string;
        data: VitalCoreSchemasResponseSchemasTimeseriesClientFacingTimeseriesGroupClientFacingForcedVitalCapacitySample.Raw;
    }
}
