/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";
import { ClientFacingSource } from "./ClientFacingSource";

export const ClientFacingProfile: core.serialization.ObjectSchema<
    serializers.ClientFacingProfile.Raw,
    Vital.ClientFacingProfile
> = core.serialization.object({
    userId: core.serialization.property("user_id", core.serialization.string()),
    id: core.serialization.string(),
    height: core.serialization.number().optional(),
    birthDate: core.serialization.property("birth_date", core.serialization.string().optional()),
    wheelchairUse: core.serialization.property("wheelchair_use", core.serialization.boolean().optional()),
    source: ClientFacingSource,
});

export declare namespace ClientFacingProfile {
    interface Raw {
        user_id: string;
        id: string;
        height?: number | null;
        birth_date?: string | null;
        wheelchair_use?: boolean | null;
        source: ClientFacingSource.Raw;
    }
}
