/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";
import { LabLocationMetadata } from "./LabLocationMetadata";
import { Billing } from "./Billing";

export const ClientFacingLabLocation: core.serialization.ObjectSchema<
    serializers.ClientFacingLabLocation.Raw,
    Vital.ClientFacingLabLocation
> = core.serialization.object({
    metadata: LabLocationMetadata,
    distance: core.serialization.number(),
    siteCode: core.serialization.property("site_code", core.serialization.string()),
    supportedBillTypes: core.serialization.property("supported_bill_types", core.serialization.list(Billing)),
});

export declare namespace ClientFacingLabLocation {
    interface Raw {
        metadata: LabLocationMetadata.Raw;
        distance: number;
        site_code: string;
        supported_bill_types: Billing.Raw[];
    }
}
