/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vital from "../../api";
import * as core from "../../core";

export const ClientFacingResource: core.serialization.Schema<
    serializers.ClientFacingResource.Raw,
    Vital.ClientFacingResource
> = core.serialization.enum_([
    "profile",
    "activity",
    "sleep",
    "body",
    "workouts",
    "workout_stream",
    "connection",
    "order",
    "result",
    "appointment",
    "glucose",
    "heartrate",
    "hrv",
    "hypnogram",
    "ige",
    "igg",
    "blood_oxygen",
    "blood_pressure",
    "cholesterol",
    "device",
    "weight",
    "fat",
    "meal",
    "water",
    "caffeine",
    "mindfulness_minutes",
    "steps",
    "calories_active",
    "distance",
    "floors_climbed",
    "respiratory_rate",
    "vo2_max",
    "calories_basal",
    "stress_level",
    "electrocardiogram_voltage",
    "sleep_stream",
]);

export declare namespace ClientFacingResource {
    type Raw =
        | "profile"
        | "activity"
        | "sleep"
        | "body"
        | "workouts"
        | "workout_stream"
        | "connection"
        | "order"
        | "result"
        | "appointment"
        | "glucose"
        | "heartrate"
        | "hrv"
        | "hypnogram"
        | "ige"
        | "igg"
        | "blood_oxygen"
        | "blood_pressure"
        | "cholesterol"
        | "device"
        | "weight"
        | "fat"
        | "meal"
        | "water"
        | "caffeine"
        | "mindfulness_minutes"
        | "steps"
        | "calories_active"
        | "distance"
        | "floors_climbed"
        | "respiratory_rate"
        | "vo2_max"
        | "calories_basal"
        | "stress_level"
        | "electrocardiogram_voltage"
        | "sleep_stream";
}
