/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";
import { ClientFacingGlucoseChangedEventType } from "./ClientFacingGlucoseChangedEventType";
import { GroupedGlucose } from "./GroupedGlucose";

export const ClientFacingGlucoseChanged: core.serialization.ObjectSchema<
    serializers.ClientFacingGlucoseChanged.Raw,
    Vital.ClientFacingGlucoseChanged
> = core.serialization.object({
    eventType: core.serialization.property("event_type", ClientFacingGlucoseChangedEventType),
    userId: core.serialization.property("user_id", core.serialization.string()),
    clientUserId: core.serialization.property("client_user_id", core.serialization.string()),
    teamId: core.serialization.property("team_id", core.serialization.string()),
    data: GroupedGlucose,
});

export declare namespace ClientFacingGlucoseChanged {
    interface Raw {
        event_type: ClientFacingGlucoseChangedEventType.Raw;
        user_id: string;
        client_user_id: string;
        team_id: string;
        data: GroupedGlucose.Raw;
    }
}
