/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";
import { ClientFacingCreatedChangedEventType } from "./ClientFacingCreatedChangedEventType";
import { ClientFacingAppointment } from "./ClientFacingAppointment";

export const ClientFacingCreatedChanged: core.serialization.ObjectSchema<
    serializers.ClientFacingCreatedChanged.Raw,
    Vital.ClientFacingCreatedChanged
> = core.serialization.object({
    eventType: core.serialization.property("event_type", ClientFacingCreatedChangedEventType),
    userId: core.serialization.property("user_id", core.serialization.string()),
    clientUserId: core.serialization.property("client_user_id", core.serialization.string()),
    teamId: core.serialization.property("team_id", core.serialization.string()),
    data: ClientFacingAppointment,
});

export declare namespace ClientFacingCreatedChanged {
    interface Raw {
        event_type: ClientFacingCreatedChangedEventType.Raw;
        user_id: string;
        client_user_id: string;
        team_id: string;
        data: ClientFacingAppointment.Raw;
    }
}
