/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";

export const ClientFacingHeartrateChangedEventType: core.serialization.Schema<
    serializers.ClientFacingHeartrateChangedEventType.Raw,
    Vital.ClientFacingHeartrateChangedEventType
> = core.serialization.enum_(["daily.data.heartrate.created", "daily.data.heartrate.updated"]);

export declare namespace ClientFacingHeartrateChangedEventType {
    type Raw = "daily.data.heartrate.created" | "daily.data.heartrate.updated";
}
