// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { HistoricalPullCompleted } from "./HistoricalPullCompleted.js";

export const ClientFacingForcedVitalCapacityHistoricalPullCompleted: core.serialization.ObjectSchema<
    serializers.ClientFacingForcedVitalCapacityHistoricalPullCompleted.Raw,
    Vital.ClientFacingForcedVitalCapacityHistoricalPullCompleted
> = core.serialization.object({
    eventType: core.serialization.property(
        "event_type",
        core.serialization.stringLiteral("historical.data.forced_vital_capacity.created"),
    ),
    userId: core.serialization.property("user_id", core.serialization.string()),
    clientUserId: core.serialization.property("client_user_id", core.serialization.string()),
    teamId: core.serialization.property("team_id", core.serialization.string()),
    data: HistoricalPullCompleted,
});

export declare namespace ClientFacingForcedVitalCapacityHistoricalPullCompleted {
    export interface Raw {
        event_type: "historical.data.forced_vital_capacity.created";
        user_id: string;
        client_user_id: string;
        team_id: string;
        data: HistoricalPullCompleted.Raw;
    }
}
