// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ClientFacingOrder } from "./ClientFacingOrder.js";
import { ClientFacingOrderChangedEventType } from "./ClientFacingOrderChangedEventType.js";

export const ClientFacingOrderChanged: core.serialization.ObjectSchema<
    serializers.ClientFacingOrderChanged.Raw,
    Vital.ClientFacingOrderChanged
> = core.serialization.object({
    eventType: core.serialization.property("event_type", ClientFacingOrderChangedEventType),
    userId: core.serialization.property("user_id", core.serialization.string()),
    clientUserId: core.serialization.property("client_user_id", core.serialization.string()),
    teamId: core.serialization.property("team_id", core.serialization.string()),
    data: ClientFacingOrder,
});

export declare namespace ClientFacingOrderChanged {
    export interface Raw {
        event_type: ClientFacingOrderChangedEventType.Raw;
        user_id: string;
        client_user_id: string;
        team_id: string;
        data: ClientFacingOrder.Raw;
    }
}
