/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vital from "../../api";
import * as core from "../../core";
import { ClientFacingTimeseriesGroupClientFacingNoteSample } from "./ClientFacingTimeseriesGroupClientFacingNoteSample";

export const ClientFacingGroupedTimeseriesResponseClientFacingNoteSample: core.serialization.ObjectSchema<
    serializers.ClientFacingGroupedTimeseriesResponseClientFacingNoteSample.Raw,
    Vital.ClientFacingGroupedTimeseriesResponseClientFacingNoteSample
> = core.serialization.object({
    groups: core.serialization.record(
        core.serialization.string(),
        core.serialization.list(ClientFacingTimeseriesGroupClientFacingNoteSample)
    ),
    next: core.serialization.string().optional(),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
});

export declare namespace ClientFacingGroupedTimeseriesResponseClientFacingNoteSample {
    interface Raw {
        groups: Record<string, ClientFacingTimeseriesGroupClientFacingNoteSample.Raw[]>;
        next?: string | null;
        next_cursor?: string | null;
    }
}
