/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";
import { ClientFacingElectrocardiogramChangedEventType } from "./ClientFacingElectrocardiogramChangedEventType";
import { ClientFacingElectrocardiogram } from "./ClientFacingElectrocardiogram";

export const ClientFacingElectrocardiogramChanged: core.serialization.ObjectSchema<
    serializers.ClientFacingElectrocardiogramChanged.Raw,
    Vital.ClientFacingElectrocardiogramChanged
> = core.serialization.object({
    eventType: core.serialization.property("event_type", ClientFacingElectrocardiogramChangedEventType),
    userId: core.serialization.property("user_id", core.serialization.string()),
    clientUserId: core.serialization.property("client_user_id", core.serialization.string()),
    teamId: core.serialization.property("team_id", core.serialization.string()),
    data: ClientFacingElectrocardiogram,
});

export declare namespace ClientFacingElectrocardiogramChanged {
    interface Raw {
        event_type: ClientFacingElectrocardiogramChangedEventType.Raw;
        user_id: string;
        client_user_id: string;
        team_id: string;
        data: ClientFacingElectrocardiogram.Raw;
    }
}
