// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ClientFacingShipment } from "./ClientFacingShipment.js";

export const ClientFacingTestkitOrder: core.serialization.ObjectSchema<
    serializers.ClientFacingTestkitOrder.Raw,
    Vital.ClientFacingTestkitOrder
> = core.serialization.object({
    id: core.serialization.string(),
    shipment: ClientFacingShipment.optional(),
    createdAt: core.serialization.property("created_at", core.serialization.date()),
    updatedAt: core.serialization.property("updated_at", core.serialization.date()),
});

export declare namespace ClientFacingTestkitOrder {
    export interface Raw {
        id: string;
        shipment?: ClientFacingShipment.Raw | null;
        created_at: string;
        updated_at: string;
    }
}
