/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";
import { ClientFacingBasalBodyTemperatureChangedEventType } from "./ClientFacingBasalBodyTemperatureChangedEventType";
import { VitalCoreSchemasResponseSchemasTimeseriesClientFacingTimeseriesGroupClientFacingBasalBodyTemperatureSample } from "./VitalCoreSchemasResponseSchemasTimeseriesClientFacingTimeseriesGroupClientFacingBasalBodyTemperatureSample";

export const ClientFacingBasalBodyTemperatureChanged: core.serialization.ObjectSchema<
    serializers.ClientFacingBasalBodyTemperatureChanged.Raw,
    Vital.ClientFacingBasalBodyTemperatureChanged
> = core.serialization.object({
    eventType: core.serialization.property("event_type", ClientFacingBasalBodyTemperatureChangedEventType),
    userId: core.serialization.property("user_id", core.serialization.string()),
    clientUserId: core.serialization.property("client_user_id", core.serialization.string()),
    teamId: core.serialization.property("team_id", core.serialization.string()),
    data: VitalCoreSchemasResponseSchemasTimeseriesClientFacingTimeseriesGroupClientFacingBasalBodyTemperatureSample,
});

export declare namespace ClientFacingBasalBodyTemperatureChanged {
    interface Raw {
        event_type: ClientFacingBasalBodyTemperatureChangedEventType.Raw;
        user_id: string;
        client_user_id: string;
        team_id: string;
        data: VitalCoreSchemasResponseSchemasTimeseriesClientFacingTimeseriesGroupClientFacingBasalBodyTemperatureSample.Raw;
    }
}
