/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";

export const ClientFacingLeanBodyMassChangedEventType: core.serialization.Schema<
    serializers.ClientFacingLeanBodyMassChangedEventType.Raw,
    Vital.ClientFacingLeanBodyMassChangedEventType
> = core.serialization.enum_(["daily.data.lean_body_mass.created", "daily.data.lean_body_mass.updated"]);

export declare namespace ClientFacingLeanBodyMassChangedEventType {
    type Raw = "daily.data.lean_body_mass.created" | "daily.data.lean_body_mass.updated";
}
