/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";
import { ClientFacingBloodPressureChangedEventType } from "./ClientFacingBloodPressureChangedEventType";
import { GroupedBloodPressure } from "./GroupedBloodPressure";

export const ClientFacingBloodPressureChanged: core.serialization.ObjectSchema<
    serializers.ClientFacingBloodPressureChanged.Raw,
    Vital.ClientFacingBloodPressureChanged
> = core.serialization.object({
    eventType: core.serialization.property("event_type", ClientFacingBloodPressureChangedEventType),
    userId: core.serialization.property("user_id", core.serialization.string()),
    clientUserId: core.serialization.property("client_user_id", core.serialization.string()),
    teamId: core.serialization.property("team_id", core.serialization.string()),
    data: GroupedBloodPressure,
});

export declare namespace ClientFacingBloodPressureChanged {
    interface Raw {
        event_type: ClientFacingBloodPressureChangedEventType.Raw;
        user_id: string;
        client_user_id: string;
        team_id: string;
        data: GroupedBloodPressure.Raw;
    }
}
