/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";
import { ClientFacingMealChangedEventType } from "./ClientFacingMealChangedEventType";
import { MealInDbBaseClientFacingSource } from "./MealInDbBaseClientFacingSource";

export const ClientFacingMealChanged: core.serialization.ObjectSchema<
    serializers.ClientFacingMealChanged.Raw,
    Vital.ClientFacingMealChanged
> = core.serialization.object({
    eventType: core.serialization.property("event_type", ClientFacingMealChangedEventType),
    userId: core.serialization.property("user_id", core.serialization.string()),
    clientUserId: core.serialization.property("client_user_id", core.serialization.string()),
    teamId: core.serialization.property("team_id", core.serialization.string()),
    data: MealInDbBaseClientFacingSource,
});

export declare namespace ClientFacingMealChanged {
    interface Raw {
        event_type: ClientFacingMealChangedEventType.Raw;
        user_id: string;
        client_user_id: string;
        team_id: string;
        data: MealInDbBaseClientFacingSource.Raw;
    }
}
