// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ClientFacingStandDurationChangedEventType: core.serialization.Schema<
    serializers.ClientFacingStandDurationChangedEventType.Raw,
    Vital.ClientFacingStandDurationChangedEventType
> = core.serialization.enum_(["daily.data.stand_duration.created", "daily.data.stand_duration.updated"]);

export declare namespace ClientFacingStandDurationChangedEventType {
    export type Raw = "daily.data.stand_duration.created" | "daily.data.stand_duration.updated";
}
