// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ClientFacingHandwashingChangedEventType } from "./ClientFacingHandwashingChangedEventType.js";
import { GroupedHandwashing } from "./GroupedHandwashing.js";

export const ClientFacingHandwashingChanged: core.serialization.ObjectSchema<
    serializers.ClientFacingHandwashingChanged.Raw,
    Vital.ClientFacingHandwashingChanged
> = core.serialization.object({
    eventType: core.serialization.property("event_type", ClientFacingHandwashingChangedEventType),
    userId: core.serialization.property("user_id", core.serialization.string()),
    clientUserId: core.serialization.property("client_user_id", core.serialization.string()),
    teamId: core.serialization.property("team_id", core.serialization.string()),
    data: GroupedHandwashing,
});

export declare namespace ClientFacingHandwashingChanged {
    export interface Raw {
        event_type: ClientFacingHandwashingChangedEventType.Raw;
        user_id: string;
        client_user_id: string;
        team_id: string;
        data: GroupedHandwashing.Raw;
    }
}
