// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Address } from "./Address.js";
import { ClientFacingPayorCodeSource } from "./ClientFacingPayorCodeSource.js";

export const ClientFacingPayorSearchResponseDeprecated: core.serialization.ObjectSchema<
    serializers.ClientFacingPayorSearchResponseDeprecated.Raw,
    Vital.ClientFacingPayorSearchResponseDeprecated
> = core.serialization.object({
    code: core.serialization.string(),
    name: core.serialization.string(),
    aliases: core.serialization.list(core.serialization.string()),
    orgAddress: core.serialization.property("org_address", Address),
    source: ClientFacingPayorCodeSource,
});

export declare namespace ClientFacingPayorSearchResponseDeprecated {
    export interface Raw {
        code: string;
        name: string;
        aliases: string[];
        org_address: Address.Raw;
        source: ClientFacingPayorCodeSource.Raw;
    }
}
