// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ClientFacingBodyChangedEventType: core.serialization.Schema<
    serializers.ClientFacingBodyChangedEventType.Raw,
    Vital.ClientFacingBodyChangedEventType
> = core.serialization.enum_(["daily.data.body.created", "daily.data.body.updated"]);

export declare namespace ClientFacingBodyChangedEventType {
    export type Raw = "daily.data.body.created" | "daily.data.body.updated";
}
