/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";
import { ClientUserIdConflict } from "./ClientUserIdConflict";

export const ClientUserIdConflictResponse: core.serialization.ObjectSchema<
    serializers.ClientUserIdConflictResponse.Raw,
    Vital.ClientUserIdConflictResponse
> = core.serialization.object({
    detail: ClientUserIdConflict,
});

export declare namespace ClientUserIdConflictResponse {
    interface Raw {
        detail: ClientUserIdConflict.Raw;
    }
}
