/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";

export const ClientFacingUvExposureChangedEventType: core.serialization.Schema<
    serializers.ClientFacingUvExposureChangedEventType.Raw,
    Vital.ClientFacingUvExposureChangedEventType
> = core.serialization.enum_(["daily.data.uv_exposure.created", "daily.data.uv_exposure.updated"]);

export declare namespace ClientFacingUvExposureChangedEventType {
    type Raw = "daily.data.uv_exposure.created" | "daily.data.uv_exposure.updated";
}
