/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";

export const ClientFacingHeartRate: core.serialization.ObjectSchema<
    serializers.ClientFacingHeartRate.Raw,
    Vital.ClientFacingHeartRate
> = core.serialization.object({
    avgBpm: core.serialization.property("avg_bpm", core.serialization.number().optional()),
    minBpm: core.serialization.property("min_bpm", core.serialization.number().optional()),
    maxBpm: core.serialization.property("max_bpm", core.serialization.number().optional()),
    restingBpm: core.serialization.property("resting_bpm", core.serialization.number().optional()),
});

export declare namespace ClientFacingHeartRate {
    interface Raw {
        avg_bpm?: number | null;
        min_bpm?: number | null;
        max_bpm?: number | null;
        resting_bpm?: number | null;
    }
}
