/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";
import { ClientFacingBodyTemperatureDeltaChangedEventType } from "./ClientFacingBodyTemperatureDeltaChangedEventType";
import { GroupedBodyTemperatureDelta } from "./GroupedBodyTemperatureDelta";

export const ClientFacingBodyTemperatureDeltaChanged: core.serialization.ObjectSchema<
    serializers.ClientFacingBodyTemperatureDeltaChanged.Raw,
    Vital.ClientFacingBodyTemperatureDeltaChanged
> = core.serialization.object({
    eventType: core.serialization.property("event_type", ClientFacingBodyTemperatureDeltaChangedEventType),
    userId: core.serialization.property("user_id", core.serialization.string()),
    clientUserId: core.serialization.property("client_user_id", core.serialization.string()),
    teamId: core.serialization.property("team_id", core.serialization.string()),
    data: GroupedBodyTemperatureDelta,
});

export declare namespace ClientFacingBodyTemperatureDeltaChanged {
    interface Raw {
        event_type: ClientFacingBodyTemperatureDeltaChangedEventType.Raw;
        user_id: string;
        client_user_id: string;
        team_id: string;
        data: GroupedBodyTemperatureDelta.Raw;
    }
}
