// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ConsentType } from "./ConsentType.js";

export const Consent: core.serialization.ObjectSchema<serializers.Consent.Raw, Vital.Consent> =
    core.serialization.object({
        consentType: ConsentType,
        version: core.serialization.string().optional(),
        timeOfConsent: core.serialization.date().optional(),
    });

export declare namespace Consent {
    export interface Raw {
        consentType: ConsentType.Raw;
        version?: string | null;
        timeOfConsent?: string | null;
    }
}
