// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const DemoProviders: core.serialization.Schema<serializers.DemoProviders.Raw, Vital.DemoProviders> =
    core.serialization.enum_(["apple_health_kit", "fitbit", "freestyle_libre", "oura"]);

export declare namespace DemoProviders {
    export type Raw = "apple_health_kit" | "fitbit" | "freestyle_libre" | "oura";
}
