/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vital from "../../api";
import * as core from "../../core";

export const DeviceV2InDb: core.serialization.ObjectSchema<serializers.DeviceV2InDb.Raw, Vital.DeviceV2InDb> =
    core.serialization.object({
        data: core.serialization.string().optional(),
        providerId: core.serialization.property("provider_id", core.serialization.string()),
        userId: core.serialization.property("user_id", core.serialization.string()),
        sourceId: core.serialization.property("source_id", core.serialization.number()),
        id: core.serialization.string(),
        source: core.serialization.lazyObject(async () => (await import("..")).ClientFacingProvider),
    });

export declare namespace DeviceV2InDb {
    interface Raw {
        data?: string | null;
        provider_id: string;
        user_id: string;
        source_id: number;
        id: string;
        source: serializers.ClientFacingProvider.Raw;
    }
}
