// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const FailureType: core.serialization.Schema<serializers.FailureType.Raw, Vital.FailureType> =
    core.serialization.enum_([
        "quantity_not_sufficient_failure",
        "collection_process_failure",
        "drop_off_failure",
        "internal_lab_failure",
        "order_entry_failure",
        "non_failure",
        "unknown_failure",
        "patient_condition_failure",
        "missing_result_calc_failure",
        "missing_demo_aoe_calc_failure",
        "insufficient_volume",
    ]);

export declare namespace FailureType {
    export type Raw =
        | "quantity_not_sufficient_failure"
        | "collection_process_failure"
        | "drop_off_failure"
        | "internal_lab_failure"
        | "order_entry_failure"
        | "non_failure"
        | "unknown_failure"
        | "patient_condition_failure"
        | "missing_result_calc_failure"
        | "missing_demo_aoe_calc_failure"
        | "insufficient_volume";
}
