/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vital from "../../api";
import * as core from "../../core";
import { ClientFacingOrder } from "./ClientFacingOrder";

export const GetOrdersResponse: core.serialization.ObjectSchema<
    serializers.GetOrdersResponse.Raw,
    Vital.GetOrdersResponse
> = core.serialization.object({
    orders: core.serialization.list(ClientFacingOrder),
    total: core.serialization.number().optional(),
    page: core.serialization.number().optional(),
    size: core.serialization.number().optional(),
});

export declare namespace GetOrdersResponse {
    interface Raw {
        orders: ClientFacingOrder.Raw[];
        total?: number | null;
        page?: number | null;
        size?: number | null;
    }
}
