/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vital from "../../api";
import * as core from "../../core";
import { ClientFacingSource } from "./ClientFacingSource";
import { ClientFacingHrvTimeseries } from "./ClientFacingHrvTimeseries";

export const GroupedHrv: core.serialization.ObjectSchema<serializers.GroupedHrv.Raw, Vital.GroupedHrv> =
    core.serialization.object({
        source: ClientFacingSource,
        data: core.serialization.list(ClientFacingHrvTimeseries),
    });

export declare namespace GroupedHrv {
    interface Raw {
        source: ClientFacingSource.Raw;
        data: ClientFacingHrvTimeseries.Raw[];
    }
}
