/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";
import { GroupKeyColumnExprGroupKey } from "./GroupKeyColumnExprGroupKey";

export const GroupKeyColumnExpr: core.serialization.ObjectSchema<
    serializers.GroupKeyColumnExpr.Raw,
    Vital.GroupKeyColumnExpr
> = core.serialization.object({
    groupKey: core.serialization.property("group_key", GroupKeyColumnExprGroupKey.optional()),
});

export declare namespace GroupKeyColumnExpr {
    interface Raw {
        group_key?: GroupKeyColumnExprGroupKey.Raw | null;
    }
}
