/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vital from "../../api";
import * as core from "../../core";
import { ClientFacingSource } from "./ClientFacingSource";
import { ClientFacingCaffeineTimeseries } from "./ClientFacingCaffeineTimeseries";

export const GroupedCaffeine: core.serialization.ObjectSchema<serializers.GroupedCaffeine.Raw, Vital.GroupedCaffeine> =
    core.serialization.object({
        source: ClientFacingSource,
        data: core.serialization.list(ClientFacingCaffeineTimeseries),
    });

export declare namespace GroupedCaffeine {
    interface Raw {
        source: ClientFacingSource.Raw;
        data: ClientFacingCaffeineTimeseries.Raw[];
    }
}
