// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ClientFacingHeartRateAlertSample } from "./ClientFacingHeartRateAlertSample.js";
import { ClientFacingSource } from "./ClientFacingSource.js";

export const GroupedHeartRateAlert: core.serialization.ObjectSchema<
    serializers.GroupedHeartRateAlert.Raw,
    Vital.GroupedHeartRateAlert
> = core.serialization.object({
    source: ClientFacingSource,
    data: core.serialization.list(ClientFacingHeartRateAlertSample),
});

export declare namespace GroupedHeartRateAlert {
    export interface Raw {
        source: ClientFacingSource.Raw;
        data: ClientFacingHeartRateAlertSample.Raw[];
    }
}
