// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GroupedBasalBodyTemperature } from "./GroupedBasalBodyTemperature.js";

export const GroupedBasalBodyTemperatureResponse: core.serialization.ObjectSchema<
    serializers.GroupedBasalBodyTemperatureResponse.Raw,
    Vital.GroupedBasalBodyTemperatureResponse
> = core.serialization.object({
    groups: core.serialization.record(
        core.serialization.string(),
        core.serialization.list(GroupedBasalBodyTemperature),
    ),
    next: core.serialization.string().optional(),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
});

export declare namespace GroupedBasalBodyTemperatureResponse {
    export interface Raw {
        groups: Record<string, GroupedBasalBodyTemperature.Raw[]>;
        next?: string | null;
        next_cursor?: string | null;
    }
}
