// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ClientFacingSource } from "./ClientFacingSource.js";
import { ClientFacingWheelchairPushSample } from "./ClientFacingWheelchairPushSample.js";

export const GroupedWheelchairPush: core.serialization.ObjectSchema<
    serializers.GroupedWheelchairPush.Raw,
    Vital.GroupedWheelchairPush
> = core.serialization.object({
    source: ClientFacingSource,
    data: core.serialization.list(ClientFacingWheelchairPushSample),
});

export declare namespace GroupedWheelchairPush {
    export interface Raw {
        source: ClientFacingSource.Raw;
        data: ClientFacingWheelchairPushSample.Raw[];
    }
}
