/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vital from "../../api";
import * as core from "../../core";

export const GroupedHeartRateResponse: core.serialization.ObjectSchema<
    serializers.GroupedHeartRateResponse.Raw,
    Vital.GroupedHeartRateResponse
> = core.serialization.object({
    groups: core.serialization.record(
        core.serialization.string(),
        core.serialization.list(core.serialization.lazyObject(async () => (await import("..")).GroupedHeartRate))
    ),
    next: core.serialization.string().optional(),
});

export declare namespace GroupedHeartRateResponse {
    interface Raw {
        groups: Record<string, serializers.GroupedHeartRate.Raw[]>;
        next?: string | null;
    }
}
