/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vital from "../../api";
import * as core from "../../core";

export const GroupedCholesterol: core.serialization.ObjectSchema<
    serializers.GroupedCholesterol.Raw,
    Vital.GroupedCholesterol
> = core.serialization.object({
    source: core.serialization.lazyObject(async () => (await import("..")).ClientFacingSource),
    data: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("..")).ClientFacingCholesterolTimeseries)
    ),
});

export declare namespace GroupedCholesterol {
    interface Raw {
        source: serializers.ClientFacingSource.Raw;
        data: serializers.ClientFacingCholesterolTimeseries.Raw[];
    }
}
