// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GroupedSleepApneaAlert } from "./GroupedSleepApneaAlert.js";

export const GroupedSleepApneaAlertResponse: core.serialization.ObjectSchema<
    serializers.GroupedSleepApneaAlertResponse.Raw,
    Vital.GroupedSleepApneaAlertResponse
> = core.serialization.object({
    groups: core.serialization.record(core.serialization.string(), core.serialization.list(GroupedSleepApneaAlert)),
    next: core.serialization.string().optional(),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
});

export declare namespace GroupedSleepApneaAlertResponse {
    export interface Raw {
        groups: Record<string, GroupedSleepApneaAlert.Raw[]>;
        next?: string | null;
        next_cursor?: string | null;
    }
}
