// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GroupedDaylightExposure } from "./GroupedDaylightExposure.js";

export const GroupedDaylightExposureResponse: core.serialization.ObjectSchema<
    serializers.GroupedDaylightExposureResponse.Raw,
    Vital.GroupedDaylightExposureResponse
> = core.serialization.object({
    groups: core.serialization.record(core.serialization.string(), core.serialization.list(GroupedDaylightExposure)),
    next: core.serialization.string().optional(),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
});

export declare namespace GroupedDaylightExposureResponse {
    export interface Raw {
        groups: Record<string, GroupedDaylightExposure.Raw[]>;
        next?: string | null;
        next_cursor?: string | null;
    }
}
