// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GroupedIgg } from "./GroupedIgg.js";

export const GroupedIggResponse: core.serialization.ObjectSchema<
    serializers.GroupedIggResponse.Raw,
    Vital.GroupedIggResponse
> = core.serialization.object({
    groups: core.serialization.record(core.serialization.string(), core.serialization.list(GroupedIgg)),
    next: core.serialization.string().optional(),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
});

export declare namespace GroupedIggResponse {
    export interface Raw {
        groups: Record<string, GroupedIgg.Raw[]>;
        next?: string | null;
        next_cursor?: string | null;
    }
}
