/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";
import { ClientFacingSource } from "./ClientFacingSource";
import { ClientFacingDistanceTimeseries } from "./ClientFacingDistanceTimeseries";

export const GroupedDistance: core.serialization.ObjectSchema<serializers.GroupedDistance.Raw, Vital.GroupedDistance> =
    core.serialization.object({
        source: ClientFacingSource,
        data: core.serialization.list(ClientFacingDistanceTimeseries),
    });

export declare namespace GroupedDistance {
    interface Raw {
        source: ClientFacingSource.Raw;
        data: ClientFacingDistanceTimeseries.Raw[];
    }
}
