// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GroupedHeartRateAlert } from "./GroupedHeartRateAlert.js";

export const GroupedHeartRateAlertResponse: core.serialization.ObjectSchema<
    serializers.GroupedHeartRateAlertResponse.Raw,
    Vital.GroupedHeartRateAlertResponse
> = core.serialization.object({
    groups: core.serialization.record(core.serialization.string(), core.serialization.list(GroupedHeartRateAlert)),
    next: core.serialization.string().optional(),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
});

export declare namespace GroupedHeartRateAlertResponse {
    export interface Raw {
        groups: Record<string, GroupedHeartRateAlert.Raw[]>;
        next?: string | null;
        next_cursor?: string | null;
    }
}
