/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vital from "../../api";
import * as core from "../../core";
import { ClientFacingSource } from "./ClientFacingSource";
import { ClientFacingCholesterolTimeseries } from "./ClientFacingCholesterolTimeseries";

export const GroupedCholesterol: core.serialization.ObjectSchema<
    serializers.GroupedCholesterol.Raw,
    Vital.GroupedCholesterol
> = core.serialization.object({
    source: ClientFacingSource,
    data: core.serialization.list(ClientFacingCholesterolTimeseries),
});

export declare namespace GroupedCholesterol {
    interface Raw {
        source: ClientFacingSource.Raw;
        data: ClientFacingCholesterolTimeseries.Raw[];
    }
}
