// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ClientFacingCaloriesActiveTimeseries } from "./ClientFacingCaloriesActiveTimeseries.js";
import { ClientFacingSource } from "./ClientFacingSource.js";

export const GroupedCaloriesActive: core.serialization.ObjectSchema<
    serializers.GroupedCaloriesActive.Raw,
    Vital.GroupedCaloriesActive
> = core.serialization.object({
    source: ClientFacingSource,
    data: core.serialization.list(ClientFacingCaloriesActiveTimeseries),
});

export declare namespace GroupedCaloriesActive {
    export interface Raw {
        source: ClientFacingSource.Raw;
        data: ClientFacingCaloriesActiveTimeseries.Raw[];
    }
}
