// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ClientFacingNoteSample } from "./ClientFacingNoteSample.js";
import { ClientFacingSource } from "./ClientFacingSource.js";

export const GroupedNote: core.serialization.ObjectSchema<serializers.GroupedNote.Raw, Vital.GroupedNote> =
    core.serialization.object({
        source: ClientFacingSource,
        data: core.serialization.list(ClientFacingNoteSample),
    });

export declare namespace GroupedNote {
    export interface Raw {
        source: ClientFacingSource.Raw;
        data: ClientFacingNoteSample.Raw[];
    }
}
