/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vital from "../../api";
import * as core from "../../core";

export const GroupedWaterResponse: core.serialization.ObjectSchema<
    serializers.GroupedWaterResponse.Raw,
    Vital.GroupedWaterResponse
> = core.serialization.object({
    groups: core.serialization.record(
        core.serialization.string(),
        core.serialization.list(core.serialization.lazyObject(async () => (await import("..")).GroupedWater))
    ),
    next: core.serialization.string().optional(),
});

export declare namespace GroupedWaterResponse {
    interface Raw {
        groups: Record<string, serializers.GroupedWater.Raw[]>;
        next?: string | null;
    }
}
