// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ClientFacingIggTimeseries } from "./ClientFacingIggTimeseries.js";
import { ClientFacingSource } from "./ClientFacingSource.js";

export const GroupedIgg: core.serialization.ObjectSchema<serializers.GroupedIgg.Raw, Vital.GroupedIgg> =
    core.serialization.object({
        source: ClientFacingSource,
        data: core.serialization.list(ClientFacingIggTimeseries),
    });

export declare namespace GroupedIgg {
    export interface Raw {
        source: ClientFacingSource.Raw;
        data: ClientFacingIggTimeseries.Raw[];
    }
}
