// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ClientFacingRespiratoryRateTimeseries } from "./ClientFacingRespiratoryRateTimeseries.js";
import { ClientFacingSource } from "./ClientFacingSource.js";

export const GroupedRespiratoryRate: core.serialization.ObjectSchema<
    serializers.GroupedRespiratoryRate.Raw,
    Vital.GroupedRespiratoryRate
> = core.serialization.object({
    source: ClientFacingSource,
    data: core.serialization.list(ClientFacingRespiratoryRateTimeseries),
});

export declare namespace GroupedRespiratoryRate {
    export interface Raw {
        source: ClientFacingSource.Raw;
        data: ClientFacingRespiratoryRateTimeseries.Raw[];
    }
}
