/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";
import { ClientFacingSource } from "./ClientFacingSource";
import { ClientFacingWorkoutDistanceSample } from "./ClientFacingWorkoutDistanceSample";

export const GroupedWorkoutDistance: core.serialization.ObjectSchema<
    serializers.GroupedWorkoutDistance.Raw,
    Vital.GroupedWorkoutDistance
> = core.serialization.object({
    source: ClientFacingSource,
    data: core.serialization.list(ClientFacingWorkoutDistanceSample),
});

export declare namespace GroupedWorkoutDistance {
    interface Raw {
        source: ClientFacingSource.Raw;
        data: ClientFacingWorkoutDistanceSample.Raw[];
    }
}
