// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ClientFacingBloodPressureTimeseries } from "./ClientFacingBloodPressureTimeseries.js";
import { ClientFacingSource } from "./ClientFacingSource.js";

export const GroupedBloodPressure: core.serialization.ObjectSchema<
    serializers.GroupedBloodPressure.Raw,
    Vital.GroupedBloodPressure
> = core.serialization.object({
    source: ClientFacingSource,
    data: core.serialization.list(ClientFacingBloodPressureTimeseries),
});

export declare namespace GroupedBloodPressure {
    export interface Raw {
        source: ClientFacingSource.Raw;
        data: ClientFacingBloodPressureTimeseries.Raw[];
    }
}
