/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";
import { VitalCoreSchemasDbSchemasLabTestHealthInsuranceAddress } from "./VitalCoreSchemasDbSchemasLabTestHealthInsuranceAddress";

export const GuarantorDetails: core.serialization.ObjectSchema<
    serializers.GuarantorDetails.Raw,
    Vital.GuarantorDetails
> = core.serialization.object({
    firstName: core.serialization.property("first_name", core.serialization.string()),
    lastName: core.serialization.property("last_name", core.serialization.string()),
    address: VitalCoreSchemasDbSchemasLabTestHealthInsuranceAddress,
    phoneNumber: core.serialization.property("phone_number", core.serialization.string()),
    householdIncome: core.serialization.property("household_income", core.serialization.number().optional()),
    householdSize: core.serialization.property("household_size", core.serialization.number().optional()),
    email: core.serialization.string().optional(),
});

export declare namespace GuarantorDetails {
    interface Raw {
        first_name: string;
        last_name: string;
        address: VitalCoreSchemasDbSchemasLabTestHealthInsuranceAddress.Raw;
        phone_number: string;
        household_income?: number | null;
        household_size?: number | null;
        email?: string | null;
    }
}
