// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Jpeg } from "./Jpeg.js";
import { Png } from "./Png.js";

export const HealthInsuranceCreateRequestFrontImage: core.serialization.Schema<
    serializers.HealthInsuranceCreateRequestFrontImage.Raw,
    Vital.HealthInsuranceCreateRequestFrontImage
> = core.serialization.undiscriminatedUnion([Jpeg, Png]);

export declare namespace HealthInsuranceCreateRequestFrontImage {
    export type Raw = Jpeg.Raw | Png.Raw;
}
