// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const IcdExcludesViolation: core.serialization.ObjectSchema<
    serializers.IcdExcludesViolation.Raw,
    Vital.IcdExcludesViolation
> = core.serialization.object({
    code: core.serialization.string(),
    conflictsWith: core.serialization.property("conflicts_with", core.serialization.string()),
    type: core.serialization.string(),
});

export declare namespace IcdExcludesViolation {
    export interface Raw {
        code: string;
        conflicts_with: string;
        type: string;
    }
}
