/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";

export const Interpretation: core.serialization.Schema<serializers.Interpretation.Raw, Vital.Interpretation> =
    core.serialization.enum_(["normal", "abnormal", "critical"]);

export declare namespace Interpretation {
    type Raw = "normal" | "abnormal" | "critical";
}
