// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const IntervalTimeseriesExprField: core.serialization.Schema<
    serializers.IntervalTimeseriesExprField.Raw,
    Vital.IntervalTimeseriesExprField
> = core.serialization.enum_([
    "source_provider",
    "source_type",
    "source_app_id",
    "source_workout_id",
    "source_sport",
    "timezone_offset",
    "type",
    "duration",
    "value",
]);

export declare namespace IntervalTimeseriesExprField {
    export type Raw =
        | "source_provider"
        | "source_type"
        | "source_app_id"
        | "source_workout_id"
        | "source_sport"
        | "timezone_offset"
        | "type"
        | "duration"
        | "value";
}
