/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";

export const LabLocationCapability: core.serialization.Schema<
    serializers.LabLocationCapability.Raw,
    Vital.LabLocationCapability
> = core.serialization.enum_(["stat", "appointment_scheduling_via_junction", "appointment_scheduling_with_lab"]);

export declare namespace LabLocationCapability {
    type Raw = "stat" | "appointment_scheduling_via_junction" | "appointment_scheduling_with_lab";
}
