/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";

export const LabResultsMetadata: core.serialization.ObjectSchema<
    serializers.LabResultsMetadata.Raw,
    Vital.LabResultsMetadata
> = core.serialization.object({
    age: core.serialization.string(),
    dob: core.serialization.string(),
    clia: core.serialization.property("clia_#", core.serialization.string().optional()),
    patient: core.serialization.string(),
    provider: core.serialization.string().optional(),
    laboratory: core.serialization.string().optional(),
    dateReported: core.serialization.property("date_reported", core.serialization.string()),
    dateCollected: core.serialization.property("date_collected", core.serialization.string().optional()),
    specimenNumber: core.serialization.property("specimen_number", core.serialization.string()),
    dateReceived: core.serialization.property("date_received", core.serialization.string().optional()),
    status: core.serialization.string().optional(),
    interpretation: core.serialization.string().optional(),
    patientId: core.serialization.property("patient_id", core.serialization.string().optional()),
    accountId: core.serialization.property("account_id", core.serialization.string().optional()),
});

export declare namespace LabResultsMetadata {
    interface Raw {
        age: string;
        dob: string;
        "clia_#"?: string | null;
        patient: string;
        provider?: string | null;
        laboratory?: string | null;
        date_reported: string;
        date_collected?: string | null;
        specimen_number: string;
        date_received?: string | null;
        status?: string | null;
        interpretation?: string | null;
        patient_id?: string | null;
        account_id?: string | null;
    }
}
