/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";

export const LabTestGenerationMethodFilter: core.serialization.Schema<
    serializers.LabTestGenerationMethodFilter.Raw,
    Vital.LabTestGenerationMethodFilter
> = core.serialization.enum_(["auto", "manual", "all"]);

export declare namespace LabTestGenerationMethodFilter {
    type Raw = "auto" | "manual" | "all";
}
