/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";

export const LibreConfig: core.serialization.ObjectSchema<serializers.LibreConfig.Raw, Vital.LibreConfig> =
    core.serialization.object({
        practiceId: core.serialization.property(
            "practice_id",
            core.serialization.record(core.serialization.string(), core.serialization.unknown())
        ),
        stripTz: core.serialization.property("strip_tz", core.serialization.boolean().optional()),
    });

export declare namespace LibreConfig {
    interface Raw {
        practice_id: Record<string, unknown>;
        strip_tz?: boolean | null;
    }
}
