// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const LngLat: core.serialization.ObjectSchema<serializers.LngLat.Raw, Vital.LngLat> = core.serialization.object({
    lng: core.serialization.number(),
    lat: core.serialization.number(),
});

export declare namespace LngLat {
    export interface Raw {
        lng: number;
        lat: number;
    }
}
