// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ClientFacingMenstrualCycle } from "./ClientFacingMenstrualCycle.js";

export const MenstrualCycleResponse: core.serialization.ObjectSchema<
    serializers.MenstrualCycleResponse.Raw,
    Vital.MenstrualCycleResponse
> = core.serialization.object({
    menstrualCycle: core.serialization.property("menstrual_cycle", core.serialization.list(ClientFacingMenstrualCycle)),
});

export declare namespace MenstrualCycleResponse {
    export interface Raw {
        menstrual_cycle: ClientFacingMenstrualCycle.Raw[];
    }
}
