// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { NoteTimeseriesExprField } from "./NoteTimeseriesExprField.js";

export const NoteTimeseriesExpr: core.serialization.ObjectSchema<
    serializers.NoteTimeseriesExpr.Raw,
    Vital.NoteTimeseriesExpr
> = core.serialization.object({
    timeseries: core.serialization.stringLiteral("note"),
    field: NoteTimeseriesExprField,
});

export declare namespace NoteTimeseriesExpr {
    export interface Raw {
        timeseries: "note";
        field: NoteTimeseriesExprField.Raw;
    }
}
