/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";

export const OrderLowLevelStatus: core.serialization.Schema<
    serializers.OrderLowLevelStatus.Raw,
    Vital.OrderLowLevelStatus
> = core.serialization.enum_([
    "ordered",
    "requisition_created",
    "requisition_bypassed",
    "transit_customer",
    "out_for_delivery",
    "with_customer",
    "transit_lab",
    "delivered_to_lab",
    "completed",
    "failure_to_deliver_to_lab",
    "failure_to_deliver_to_customer",
    "problem_in_transit_lab",
    "problem_in_transit_customer",
    "sample_error",
    "appointment_scheduled",
    "appointment_cancelled",
    "appointment_pending",
    "draw_completed",
    "cancelled",
    "lost",
    "do_not_process",
    "partial_results",
    "awaiting_registration",
    "registered",
    "redraw_available",
]);

export declare namespace OrderLowLevelStatus {
    type Raw =
        | "ordered"
        | "requisition_created"
        | "requisition_bypassed"
        | "transit_customer"
        | "out_for_delivery"
        | "with_customer"
        | "transit_lab"
        | "delivered_to_lab"
        | "completed"
        | "failure_to_deliver_to_lab"
        | "failure_to_deliver_to_customer"
        | "problem_in_transit_lab"
        | "problem_in_transit_customer"
        | "sample_error"
        | "appointment_scheduled"
        | "appointment_cancelled"
        | "appointment_pending"
        | "draw_completed"
        | "cancelled"
        | "lost"
        | "do_not_process"
        | "partial_results"
        | "awaiting_registration"
        | "registered"
        | "redraw_available";
}
