// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { OvulationTestEntryTestResult } from "./OvulationTestEntryTestResult.js";

export const OvulationTestEntry: core.serialization.ObjectSchema<
    serializers.OvulationTestEntry.Raw,
    Vital.OvulationTestEntry
> = core.serialization.object({
    date: core.serialization.string(),
    testResult: core.serialization.property("test_result", OvulationTestEntryTestResult),
});

export declare namespace OvulationTestEntry {
    export interface Raw {
        date: string;
        test_result: OvulationTestEntryTestResult.Raw;
    }
}
