// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Ethnicity } from "./Ethnicity.js";
import { Gender } from "./Gender.js";
import { GenderIdentity } from "./GenderIdentity.js";
import { GuarantorDetails } from "./GuarantorDetails.js";
import { Race } from "./Race.js";
import { SexualOrientation } from "./SexualOrientation.js";

export const PatientDetailsWithValidation: core.serialization.ObjectSchema<
    serializers.PatientDetailsWithValidation.Raw,
    Vital.PatientDetailsWithValidation
> = core.serialization.object({
    firstName: core.serialization.property("first_name", core.serialization.string()),
    lastName: core.serialization.property("last_name", core.serialization.string()),
    dob: core.serialization.string(),
    gender: Gender,
    phoneNumber: core.serialization.property("phone_number", core.serialization.string()),
    email: core.serialization.string(),
    medicalProxy: core.serialization.property("medical_proxy", GuarantorDetails.optional()),
    race: Race.optional(),
    ethnicity: Ethnicity.optional(),
    sexualOrientation: core.serialization.property("sexual_orientation", SexualOrientation.optional()),
    genderIdentity: core.serialization.property("gender_identity", GenderIdentity.optional()),
    householdIncome: core.serialization.property("household_income", core.serialization.number().optional()),
    householdSize: core.serialization.property("household_size", core.serialization.number().optional()),
});

export declare namespace PatientDetailsWithValidation {
    export interface Raw {
        first_name: string;
        last_name: string;
        dob: string;
        gender: Gender.Raw;
        phone_number: string;
        email: string;
        medical_proxy?: GuarantorDetails.Raw | null;
        race?: Race.Raw | null;
        ethnicity?: Ethnicity.Raw | null;
        sexual_orientation?: SexualOrientation.Raw | null;
        gender_identity?: GenderIdentity.Raw | null;
        household_income?: number | null;
        household_size?: number | null;
    }
}
