/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";
import { VitalCoreSchemasDbSchemasLabTestInsuranceAddress } from "./VitalCoreSchemasDbSchemasLabTestInsuranceAddress";

export const PerformingLaboratory: core.serialization.ObjectSchema<
    serializers.PerformingLaboratory.Raw,
    Vital.PerformingLaboratory
> = core.serialization.object({
    name: core.serialization.string(),
    phoneNumber: core.serialization.property("phone_number", core.serialization.string().optional()),
    medicalDirector: core.serialization.property("medical_director", core.serialization.string().optional()),
    address: VitalCoreSchemasDbSchemasLabTestInsuranceAddress.optional(),
});

export declare namespace PerformingLaboratory {
    interface Raw {
        name: string;
        phone_number?: string | null;
        medical_director?: string | null;
        address?: VitalCoreSchemasDbSchemasLabTestInsuranceAddress.Raw | null;
    }
}
