/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vital from "../../api";
import * as core from "../../core";

export const PersonDetails: core.serialization.ObjectSchema<serializers.PersonDetails.Raw, Vital.PersonDetails> =
    core.serialization.object({
        firstName: core.serialization.property("first_name", core.serialization.string()),
        lastName: core.serialization.property("last_name", core.serialization.string()),
        address: core.serialization.lazyObject(async () => (await import("..")).Address),
        phoneNumber: core.serialization.property("phone_number", core.serialization.string()),
        phoneType: core.serialization.property("phone_type", core.serialization.string().optional()),
    });

export declare namespace PersonDetails {
    interface Raw {
        first_name: string;
        last_name: string;
        address: serializers.Address.Raw;
        phone_number: string;
        phone_type?: string | null;
    }
}
