/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";
import { QuerySelectItem } from "./QuerySelectItem";
import { QueryGroupByItem } from "./QueryGroupByItem";

export const Query: core.serialization.ObjectSchema<serializers.Query.Raw, Vital.Query> = core.serialization.object({
    select: core.serialization.list(QuerySelectItem),
    groupBy: core.serialization.property("group_by", core.serialization.list(QueryGroupByItem).optional()),
});

export declare namespace Query {
    interface Raw {
        select: QuerySelectItem.Raw[];
        group_by?: QueryGroupByItem.Raw[] | null;
    }
}
