/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";
import { Providers } from "./Providers";
import { Labs } from "./Labs";

export const QueryConfigProviderPriorityOverridesItem: core.serialization.Schema<
    serializers.QueryConfigProviderPriorityOverridesItem.Raw,
    Vital.QueryConfigProviderPriorityOverridesItem
> = core.serialization.undiscriminatedUnion([Providers, Labs]);

export declare namespace QueryConfigProviderPriorityOverridesItem {
    type Raw = Providers.Raw | Labs.Raw;
}
