// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ProfileInDb } from "./ProfileInDb.js";

export const RawProfile: core.serialization.ObjectSchema<serializers.RawProfile.Raw, Vital.RawProfile> =
    core.serialization.object({
        profile: ProfileInDb,
    });

export declare namespace RawProfile {
    export interface Raw {
        profile: ProfileInDb.Raw;
    }
}
