/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";
import { ReducerFunction } from "./ReducerFunction";

export const Reducer: core.serialization.ObjectSchema<serializers.Reducer.Raw, Vital.Reducer> =
    core.serialization.object({
        function: ReducerFunction,
    });

export declare namespace Reducer {
    interface Raw {
        function: ReducerFunction.Raw;
    }
}
