/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vital from "../../api";
import * as core from "../../core";
import { Availability } from "./Availability";
import { ScopeRequirementsGrants } from "./ScopeRequirementsGrants";

export const ResourceAvailability: core.serialization.ObjectSchema<
    serializers.ResourceAvailability.Raw,
    Vital.ResourceAvailability
> = core.serialization.object({
    status: Availability,
    scopeRequirements: core.serialization.property("scope_requirements", ScopeRequirementsGrants.optional()),
});

export declare namespace ResourceAvailability {
    interface Raw {
        status: Availability.Raw;
        scope_requirements?: ScopeRequirementsGrants.Raw | null;
    }
}
