// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ResultMetadata: core.serialization.ObjectSchema<serializers.ResultMetadata.Raw, Vital.ResultMetadata> =
    core.serialization.object({
        patientFirstName: core.serialization.property("patient_first_name", core.serialization.string().optional()),
        patientLastName: core.serialization.property("patient_last_name", core.serialization.string().optional()),
        dob: core.serialization.string().optional(),
        labName: core.serialization.property("lab_name", core.serialization.string().optional()),
        dateReported: core.serialization.property("date_reported", core.serialization.string().optional()),
        dateCollected: core.serialization.property("date_collected", core.serialization.string().optional()),
        specimenNumber: core.serialization.property("specimen_number", core.serialization.string().optional()),
    });

export declare namespace ResultMetadata {
    export interface Raw {
        patient_first_name?: string | null;
        patient_last_name?: string | null;
        dob?: string | null;
        lab_name?: string | null;
        date_reported?: string | null;
        date_collected?: string | null;
        specimen_number?: string | null;
    }
}
