// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { SingleProviderHistoricalPullResponse } from "./SingleProviderHistoricalPullResponse.js";

export const SingleUserHistoricalPullResponse: core.serialization.ObjectSchema<
    serializers.SingleUserHistoricalPullResponse.Raw,
    Vital.SingleUserHistoricalPullResponse
> = core.serialization.object({
    userId: core.serialization.property("user_id", core.serialization.string()),
    provider: core.serialization.record(core.serialization.string(), SingleProviderHistoricalPullResponse),
});

export declare namespace SingleUserHistoricalPullResponse {
    export interface Raw {
        user_id: string;
        provider: Record<string, SingleProviderHistoricalPullResponse.Raw>;
    }
}
