/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";
import { SingleResourceStatistics } from "./SingleResourceStatistics";

export const SingleUserResourceResponse: core.serialization.ObjectSchema<
    serializers.SingleUserResourceResponse.Raw,
    Vital.SingleUserResourceResponse
> = core.serialization.object({
    userId: core.serialization.property("user_id", core.serialization.string()),
    provider: core.serialization.record(
        core.serialization.string(),
        core.serialization.record(core.serialization.string(), SingleResourceStatistics)
    ),
});

export declare namespace SingleUserResourceResponse {
    interface Raw {
        user_id: string;
        provider: Record<string, Record<string, SingleResourceStatistics.Raw>>;
    }
}
