// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { SleepColumnExprSleep } from "./SleepColumnExprSleep.js";

export const SleepColumnExpr: core.serialization.ObjectSchema<serializers.SleepColumnExpr.Raw, Vital.SleepColumnExpr> =
    core.serialization.object({
        sleep: SleepColumnExprSleep,
    });

export declare namespace SleepColumnExpr {
    export interface Raw {
        sleep: SleepColumnExprSleep.Raw;
    }
}
