/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";

export const SleepCycleSourceType: core.serialization.Schema<
    serializers.SleepCycleSourceType.Raw,
    Vital.SleepCycleSourceType
> = core.serialization.enum_([
    "unknown",
    "phone",
    "watch",
    "app",
    "multiple_sources",
    "fingerprick",
    "cuff",
    "manual_scan",
    "automatic",
    "scale",
    "chest_strap",
    "ring",
    "lab",
]);

export declare namespace SleepCycleSourceType {
    type Raw =
        | "unknown"
        | "phone"
        | "watch"
        | "app"
        | "multiple_sources"
        | "fingerprick"
        | "cuff"
        | "manual_scan"
        | "automatic"
        | "scale"
        | "chest_strap"
        | "ring"
        | "lab";
}
