// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const SleepScoreValueMacroExpr: core.serialization.ObjectSchema<
    serializers.SleepScoreValueMacroExpr.Raw,
    Vital.SleepScoreValueMacroExpr
> = core.serialization.object({
    valueMacro: core.serialization.property("value_macro", core.serialization.stringLiteral("sleep_score")),
    version: core.serialization.stringLiteral("automatic").optional(),
});

export declare namespace SleepScoreValueMacroExpr {
    export interface Raw {
        value_macro: "sleep_score";
        version?: "automatic" | null;
    }
}
