/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";
import { SourceColumnExprSource } from "./SourceColumnExprSource";

export const SourceColumnExpr: core.serialization.ObjectSchema<
    serializers.SourceColumnExpr.Raw,
    Vital.SourceColumnExpr
> = core.serialization.object({
    source: SourceColumnExprSource,
});

export declare namespace SourceColumnExpr {
    interface Raw {
        source: SourceColumnExprSource.Raw;
    }
}
