/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";

export const TemperatureTimeseriesExprTimeseries: core.serialization.Schema<
    serializers.TemperatureTimeseriesExprTimeseries.Raw,
    Vital.TemperatureTimeseriesExprTimeseries
> = core.serialization.enum_(["body_temperature", "body_temperature_delta"]);

export declare namespace TemperatureTimeseriesExprTimeseries {
    type Raw = "body_temperature" | "body_temperature_delta";
}
