// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { SingleUserHistoricalPullResponse } from "./SingleUserHistoricalPullResponse.js";

export const UserHistoricalPullsResponse: core.serialization.ObjectSchema<
    serializers.UserHistoricalPullsResponse.Raw,
    Vital.UserHistoricalPullsResponse
> = core.serialization.object({
    data: core.serialization.list(SingleUserHistoricalPullResponse),
    next: core.serialization.string().optional(),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
});

export declare namespace UserHistoricalPullsResponse {
    export interface Raw {
        data: SingleUserHistoricalPullResponse.Raw[];
        next?: string | null;
        next_cursor?: string | null;
    }
}
