/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vital from "../../api";
import * as core from "../../core";

export const UserResourcesResponse: core.serialization.ObjectSchema<
    serializers.UserResourcesResponse.Raw,
    Vital.UserResourcesResponse
> = core.serialization.object({
    data: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("..")).SingleUserResourceResponse)
    ),
    next: core.serialization.string().optional(),
});

export declare namespace UserResourcesResponse {
    interface Raw {
        data: serializers.SingleUserResourceResponse.Raw[];
        next?: string | null;
    }
}
