// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { IcdExcludesViolation } from "./IcdExcludesViolation.js";
import { IcdExcludesWarning } from "./IcdExcludesWarning.js";

export const ValidateIcdCodesResponse: core.serialization.ObjectSchema<
    serializers.ValidateIcdCodesResponse.Raw,
    Vital.ValidateIcdCodesResponse
> = core.serialization.object({
    valid: core.serialization.boolean(),
    errors: core.serialization.list(core.serialization.string()),
    violations: core.serialization.list(IcdExcludesViolation),
    warnings: core.serialization.list(IcdExcludesWarning),
});

export declare namespace ValidateIcdCodesResponse {
    export interface Raw {
        valid: boolean;
        errors: string[];
        violations: IcdExcludesViolation.Raw[];
        warnings: IcdExcludesWarning.Raw[];
    }
}
