/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vital from "../../api";
import * as core from "../../core";
import { VitalCoreProvidersLabTestLabsSchemasResultsFhirEntryItemResource } from "./VitalCoreProvidersLabTestLabsSchemasResultsFhirEntryItemResource";

export const VitalCoreProvidersLabTestLabsSchemasResultsFhirEntryItem: core.serialization.ObjectSchema<
    serializers.VitalCoreProvidersLabTestLabsSchemasResultsFhirEntryItem.Raw,
    Vital.VitalCoreProvidersLabTestLabsSchemasResultsFhirEntryItem
> = core.serialization.object({
    resource: VitalCoreProvidersLabTestLabsSchemasResultsFhirEntryItemResource,
});

export declare namespace VitalCoreProvidersLabTestLabsSchemasResultsFhirEntryItem {
    interface Raw {
        resource: VitalCoreProvidersLabTestLabsSchemasResultsFhirEntryItemResource.Raw;
    }
}
