// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Address } from "./Address.js";

export const VitalCoreSchemasDbSchemasLabTestHealthInsurancePersonDetails: core.serialization.ObjectSchema<
    serializers.VitalCoreSchemasDbSchemasLabTestHealthInsurancePersonDetails.Raw,
    Vital.VitalCoreSchemasDbSchemasLabTestHealthInsurancePersonDetails
> = core.serialization.object({
    firstName: core.serialization.property("first_name", core.serialization.string()),
    lastName: core.serialization.property("last_name", core.serialization.string()),
    address: Address,
    phoneNumber: core.serialization.property("phone_number", core.serialization.string()),
    phoneType: core.serialization.property("phone_type", core.serialization.string().optional()),
});

export declare namespace VitalCoreSchemasDbSchemasLabTestHealthInsurancePersonDetails {
    export interface Raw {
        first_name: string;
        last_name: string;
        address: Address.Raw;
        phone_number: string;
        phone_type?: string | null;
    }
}
