/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";
import { ClientFacingSource } from "./ClientFacingSource";
import { ClientFacingCarbohydratesSample } from "./ClientFacingCarbohydratesSample";

export const VitalCoreSchemasResponseSchemasTimeseriesClientFacingTimeseriesGroupClientFacingCarbohydratesSample: core.serialization.ObjectSchema<
    serializers.VitalCoreSchemasResponseSchemasTimeseriesClientFacingTimeseriesGroupClientFacingCarbohydratesSample.Raw,
    Vital.VitalCoreSchemasResponseSchemasTimeseriesClientFacingTimeseriesGroupClientFacingCarbohydratesSample
> = core.serialization.object({
    source: ClientFacingSource,
    data: core.serialization.list(ClientFacingCarbohydratesSample),
});

export declare namespace VitalCoreSchemasResponseSchemasTimeseriesClientFacingTimeseriesGroupClientFacingCarbohydratesSample {
    interface Raw {
        source: ClientFacingSource.Raw;
        data: ClientFacingCarbohydratesSample.Raw[];
    }
}
