/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vital from "../../api/index";
import * as core from "../../core";
import { ClientFacingSource } from "./ClientFacingSource";
import { ClientFacingHeartRateRecoveryOneMinuteSample } from "./ClientFacingHeartRateRecoveryOneMinuteSample";

export const VitalCoreSchemasResponseSchemasTimeseriesClientFacingTimeseriesGroupClientFacingHeartRateRecoveryOneMinuteSample: core.serialization.ObjectSchema<
    serializers.VitalCoreSchemasResponseSchemasTimeseriesClientFacingTimeseriesGroupClientFacingHeartRateRecoveryOneMinuteSample.Raw,
    Vital.VitalCoreSchemasResponseSchemasTimeseriesClientFacingTimeseriesGroupClientFacingHeartRateRecoveryOneMinuteSample
> = core.serialization.object({
    source: ClientFacingSource,
    data: core.serialization.list(ClientFacingHeartRateRecoveryOneMinuteSample),
});

export declare namespace VitalCoreSchemasResponseSchemasTimeseriesClientFacingTimeseriesGroupClientFacingHeartRateRecoveryOneMinuteSample {
    interface Raw {
        source: ClientFacingSource.Raw;
        data: ClientFacingHeartRateRecoveryOneMinuteSample.Raw[];
    }
}
