/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vital from "../../api";
import * as core from "../../core";

export const VitalCoreProvidersLabTestLabsSchemasResultsFhirIdentifierItem: core.serialization.ObjectSchema<
    serializers.VitalCoreProvidersLabTestLabsSchemasResultsFhirIdentifierItem.Raw,
    Vital.VitalCoreProvidersLabTestLabsSchemasResultsFhirIdentifierItem
> = core.serialization.object({
    value: core.serialization.string(),
});

export declare namespace VitalCoreProvidersLabTestLabsSchemasResultsFhirIdentifierItem {
    interface Raw {
        value: string;
    }
}
