/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Vital from "../../../../api";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.providers.getListOfProviders.Response.Raw,
    Vital.ClientFacingProviderDetailed[]
> = core.serialization.list(
    core.serialization.lazyObject(async () => (await import("../../..")).ClientFacingProviderDetailed)
);

export declare namespace Response {
    type Raw = serializers.ClientFacingProviderDetailed.Raw[];
}
