/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface ProfileGetRequest {
    /**
     * Provider oura/strava etc
     */
    provider?: string;
}
