// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const LabTestsGetPaginatedRequestOrderDirection: core.serialization.Schema<
    serializers.LabTestsGetPaginatedRequestOrderDirection.Raw,
    Vital.LabTestsGetPaginatedRequestOrderDirection
> = core.serialization.enum_(["asc", "desc"]);

export declare namespace LabTestsGetPaginatedRequestOrderDirection {
    export type Raw = "asc" | "desc";
}
