/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Vital from "../../../../api/index";
import * as core from "../../../../core";

export const LabTestsGetRequestOrderKey: core.serialization.Schema<
    serializers.LabTestsGetRequestOrderKey.Raw,
    Vital.LabTestsGetRequestOrderKey
> = core.serialization.enum_(["price", "created_at", "updated_at"]);

export declare namespace LabTestsGetRequestOrderKey {
    type Raw = "price" | "created_at" | "updated_at";
}
