// This file was auto-generated by Fern from our API Definition.

import type * as Vital from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { ClientFacingProviderWithStatus } from "../../../types/ClientFacingProviderWithStatus.js";

export const Response: core.serialization.Schema<
    serializers.user.getConnectedProviders.Response.Raw,
    Record<string, Vital.ClientFacingProviderWithStatus[]>
> = core.serialization.record(core.serialization.string(), core.serialization.list(ClientFacingProviderWithStatus));

export declare namespace Response {
    export type Raw = Record<string, ClientFacingProviderWithStatus.Raw[]>;
}
