// This file was auto-generated by Fern from our API Definition.

export const VitalEnvironment = {
    Production: "https://api.tryvital.io",
    ProductionEu: "https://api.eu.tryvital.io",
    Sandbox: "https://api.sandbox.tryvital.io",
    SandboxEu: "https://api.sandbox.eu.tryvital.io",
} as const;

export type VitalEnvironment =
    | typeof VitalEnvironment.Production
    | typeof VitalEnvironment.ProductionEu
    | typeof VitalEnvironment.Sandbox
    | typeof VitalEnvironment.SandboxEu;
